// AUTO-GENERATED by scripts/extract-narratives.ts from the eval-form template.
// Run `npm run extract:narratives` to regenerate. Hand-edits will be overwritten.

import type { MarkerNarrative, GroupNarrative } from "./types";

export const MARKER_NARRATIVES: Record<string, MarkerNarrative> = {
  "% Iron Saturation": {
    canonicalName: "% Iron Saturation",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "A/G Ratio": {
    canonicalName: "A/G Ratio",
    description: `An abnormal A/G ratio, often called a suppressed, low or reversed ratio is generally considered a reflection of hepatic dysfunction.`,
    increaseCauses: [
          "not considered significant"
    ],
    decreaseCauses: [
          "Liver/biliary dysfunction",
          "Chronic renal disease",
          "Some types of cancer",
          "Sarcoidosis",
          "Collagen diseases",
          "Severe infections",
          "Systemic inflammation",
          "Burns",
          "Digestive inflammation"
    ],
    additionalProse: null,
  },
  "ABO Group": {
    canonicalName: "ABO Group",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "ALT (Alanine Aminotransferase)": {
    canonicalName: "ALT (Alanine Aminotransferase)",
    description: `ALT is used to identify hepatocellular disease.`,
    increaseCauses: [
          "Cirrhosis of the liver",
          "Acute and chronic liver necrosis",
          "Hepatitis/mononucleosis",
          "Epstein-Barr virus and cytomegalovirus",
          "Acetaminophen"
    ],
    decreaseCauses: [
          "Vitamin B6 anemia"
    ],
    additionalProse: null,
  },
  "AMH (Anti-Mullerian Hormone)": {
    canonicalName: "AMH (Anti-Mullerian Hormone)",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "ANA (Anti-nuclear Antibodies)": {
    canonicalName: "ANA (Anti-nuclear Antibodies)",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "AST (Aspartate Aminotransferase)": {
    canonicalName: "AST (Aspartate Aminotransferase)",
    description: `AST is an enzyme found in high concentrations in the heart, liver, skeleton, muscles, kidneys and pancreas.`,
    increaseCauses: [
          "Heart disease",
          "Liver disease",
          "Musculoskeletal",
          "Congestive heart failure",
          "Acute pancreatitis",
          "Liver dysfunction due to EBV disrupting detoxification and the liver compensating."
    ],
    decreaseCauses: [
          "Vitamin B6 anemia",
          "Renal disease"
    ],
    additionalProse: null,
  },
  "Albumin": {
    canonicalName: "Albumin",
    description: `Albumin is produced almost entirely by the liver, therefore liver function has a major influence on albumin production and serum albumin levels. Decreased albumin is always an indication of significant liver or immune dysfunction. When albumin is decreased and globulins are increased, chronic liver disease is generally suspected.`,
    increaseCauses: [
          "Dehydration"
    ],
    decreaseCauses: [
          "Liver/biliary dysfunction",
          "Neoplasm",
          "Protein malnutrition/amino acid need"
    ],
    additionalProse: null,
  },
  "Albumin Urine": {
    canonicalName: "Albumin Urine",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Alkaline Phosphatase": {
    canonicalName: "Alkaline Phosphatase",
    description: `ALP is a member of a family of zinc metalloprotein enzymes. A decrease in ALP is frequently associated with a zinc deficiency.`,
    increaseCauses: [
          "Healing fracture",
          "Liver cancer",
          "Cirrhosis",
          "Normal pregnancy (3rd trimester)",
          "Impairment of bile flow",
          "Paget's disease of bone"
    ],
    decreaseCauses: [
          "Biliary obstruction",
          "Zinc deficiency",
          "Vitamin C insufficiency"
    ],
    additionalProse: null,
  },
  "Amylase": {
    canonicalName: "Amylase",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Apoliopoprotein B": {
    canonicalName: "Apoliopoprotein B",
    description: `High levels of ApoB correspond to higher levels of “bad” cholesterol (LDL and VLDL cholesterol) and are associated with a higher risk of heart disease.
ApoB represents the total number of atherogenic particles (LDL, VLDL, IDL, Lp(a)).
Each atherogenic particle has one ApoB, so ApoB = particle count.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: {
        intro: `High ApoB means:`,
        bullets: [
          `Too many plaque-forming particles`,
          `Increased arterial wall penetration`,
          `Higher ASCVD risk even if LDL-C looks “normal”`,
          `Need a CAC test - calcium score test to truly confirm`,
        ],
      },
  },
  "Arachidonic Acid": {
    canonicalName: "Arachidonic Acid",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Arachidonic Acid/EPA Ratio": {
    canonicalName: "Arachidonic Acid/EPA Ratio",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "BUN (Blood Urea Nitrogen)": {
    canonicalName: "BUN (Blood Urea Nitrogen)",
    description: `BUN reflects the difference between production and clearance of urea. Urea is the chief end product of protein metabolism and is formed almost entirely by the liver through the urea cycle. It is removed almost entirely by the kidneys.`,
    increaseCauses: [
          "Chronic renal dysfunction",
          "Renal hypertension",
          "Prescribed diuretics",
          "Dehydration",
          "Liver stress",
          "Benin prostate hypertrophy – men",
          "Urinary obstruction"
    ],
    decreaseCauses: [
          "Liver failure/stress",
          "Protein malnutrition",
          "Celiac/wheat intolerance"
    ],
    additionalProse: null,
  },
  "BUN/Creatinine Ratio": {
    canonicalName: "BUN/Creatinine Ratio",
    description: `BUN/Creatinine Ratio is useful when assessing patients with chronic renal dysfunction.`,
    increaseCauses: [
          "Congestive heart failure",
          "Intestinal bleeding",
          "Shock",
          "Hypotension",
          "Dehydration",
          "Renal disease"
    ],
    decreaseCauses: [
          "Low protein diets",
          "Malnutrition"
    ],
    additionalProse: null,
  },
  "Basophils": {
    canonicalName: "Basophils",
    description: `During inflammation basophils deliver heparin to the inflamed tissues to prevent clotting. Basophils will almost always be increased with tissue inflammation.`,
    increaseCauses: [
          "Tissue inflammation",
          "Intestinal parasites",
          "Polycythemia"
    ],
    decreaseCauses: [
          "Stress",
          "Acute allergic reactions",
          "Hyperthyroidism"
    ],
    additionalProse: null,
  },
  "CO2 (Carbon Dioxide)": {
    canonicalName: "CO2 (Carbon Dioxide)",
    description: `CO2 is the amount of base bound as bicarbonate in the blood that is available for the neutralizations of fixed acids such as lactic acid and hydrochloric acid.`,
    increaseCauses: [
          "Metabolic alkalosis",
          "Vomiting"
    ],
    decreaseCauses: [
          "Thiamine deficiency, anion gap is generally increased",
          "Diabetes",
          "Metabolic acidosis – end product of food breakdown is more acidic"
    ],
    additionalProse: null,
  },
  "Cacao": {
    canonicalName: "Cacao",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Calcium": {
    canonicalName: "Calcium",
    description: `Calcium is absorbed from the upper part of the small intestine. The amount of absorption depends on the acidity of the intestinal contents and the amount of phosphate present. Calcium relates to bone metabolism, the drawing of fats through the intestinal wall and protein absorption. The amount of protein in the blood affects the calcium level. Calcium is used rapidly for repair of tissue conjugation with vitamin A, vitamin C, magnesium, phosphorus, iodine, and unsaturated fatty acids.`,
    increaseCauses: [
          "Parathyroid hyperfunction",
          "Cancer",
          "Hypervitaminosis D",
          "Sarcoidosis"
    ],
    decreaseCauses: [
          "Parathyroid hypofunction",
          "Digestive dysfunction (hypochlorhydria)",
          "Low/normal total protein or albumin",
          "Vitamin D insufficiency",
          "Protein malnutrition",
          "Osteoporosis",
          "Pancreatitis"
    ],
    additionalProse: null,
  },
  "Candida Albicans": {
    canonicalName: "Candida Albicans",
    description: `Overgrowth of Candida Albicans in the GI tract can exacerbate many symptoms of leaky gut including fatigue, joint pain, gas, bloating, and irritability. Although Candida is normally found in the gut it is common for it to overpopulate, damage the gut wall, and release toxic byproducts into the body. Acetaldehyde is a common waste product of candida and can lead to nausea and headaches.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Casein": {
    canonicalName: "Casein",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Chloride": {
    canonicalName: "Chloride",
    description: `Chloride is the principle ion found in serum. Chloride level along with sodium, potassium and CO2 are important for evaluating acid-base relationships, state of hydration, as well as adrenal and renal function. Increased chloride is commonly associated with renal or systemic acidosis and decreased chloride with systemic alkalosis.`,
    increaseCauses: [
          "Renal dysfunction",
          "Dehydration"
    ],
    decreaseCauses: [
          "Hypochlorhydria – lack of stomach acid"
    ],
    additionalProse: null,
  },
  "Cholesterol": {
    canonicalName: "Cholesterol",
    description: `Cholesterol is a steroid normally found in all body cells and plasma.`,
    increaseCauses: [
          "Coronary artery disease",
          "Diabetes",
          "Primary thyroid hypofunction or hypofunction secondary to anterior pituitary hypofunction.",
          "Liver dysfunction due to lack of detoxification caused by EBV.",
          "Poor fat metabolism"
    ],
    decreaseCauses: [
          "Thyroid hyperfunction and/or anterior pituitary hyperfunction",
          "Cancer",
          "Crohn's disease",
          "Cirrhosis of the liver",
          "Celiac disease",
          "Malnutrition"
    ],
    additionalProse: null,
  },
  "Corn": {
    canonicalName: "Corn",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Cortisol": {
    canonicalName: "Cortisol",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Creatinine": {
    canonicalName: "Creatinine",
    description: `Creatinine testing is used to diagnose impaired renal function. Patients with increased muscle mass may have slightly higher creatinine levels and patients with decreased muscle mass will have slightly lower levels of creatinine.`,
    increaseCauses: [
          "Chronic renal dysfunction",
          "Benign prostate hypertrophy"
    ],
    decreaseCauses: [
          "Patients who have less than average muscle mass – due the liver being affected by EBV and not being able to generate protein properly"
    ],
    additionalProse: null,
  },
  "DHA": {
    canonicalName: "DHA",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "DHEA Sulfate": {
    canonicalName: "DHEA Sulfate",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "DPA": {
    canonicalName: "DPA",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "EBV Early Antigen IgG": {
    canonicalName: "EBV Early Antigen IgG",
    description: `Indicates reactivation of a previous infection
Epstein-Barr virus (EBV) – A member of the herpes family of viruses, EBV infects most people during some point of their lives. When infection occurs during adolescence or young adulthood, it causes infectious mononucleosis 35% to 50% of the time. Symptoms of infectious mononucleosis are fever, sore throat, swollen lymph glands and extreme fatigue. Rarely a swollen spleen or liver involvement may develop; even more rarely heart problems and central nervous system involvement occur. Transmission of EBV requires intimate contact with the saliva of an infected person.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "EBV Nuclear AG IgG": {
    canonicalName: "EBV Nuclear AG IgG",
    description: `Indicates reactivation of a previous infection
Epstein-Barr virus (EBV) – A member of the herpes family of viruses, EBV infects most people during some point of their lives. When infection occurs during adolescence or young adulthood, it causes infectious mononucleosis 35% to 50% of the time. Symptoms of infectious mononucleosis are fever, sore throat, swollen lymph glands and extreme fatigue. Rarely a swollen spleen or liver involvement may develop; even more rarely heart problems and central nervous system involvement occur. Transmission of EBV requires intimate contact with the saliva of an infected person.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "EBV Viral Capsid IgG": {
    canonicalName: "EBV Viral Capsid IgG",
    description: `Indicates reactivation of a previous infection
Epstein-Barr virus (EBV) – A member of the herpes family of viruses, EBV infects most people during some point of their lives. When infection occurs during adolescence or young adulthood, it causes infectious mononucleosis 35% to 50% of the time. Symptoms of infectious mononucleosis are fever, sore throat, swollen lymph glands and extreme fatigue. Rarely a swollen spleen or liver involvement may develop; even more rarely heart problems and central nervous system involvement occur. Transmission of EBV requires intimate contact with the saliva of an infected person.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "EBV Viral Capsid IgM": {
    canonicalName: "EBV Viral Capsid IgM",
    description: `Indicates reactivation of a previous infection
Epstein-Barr virus (EBV) – A member of the herpes family of viruses, EBV infects most people during some point of their lives. When infection occurs during adolescence or young adulthood, it causes infectious mononucleosis 35% to 50% of the time. Symptoms of infectious mononucleosis are fever, sore throat, swollen lymph glands and extreme fatigue. Rarely a swollen spleen or liver involvement may develop; even more rarely heart problems and central nervous system involvement occur. Transmission of EBV requires intimate contact with the saliva of an infected person.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "EPA": {
    canonicalName: "EPA",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Eggwhite": {
    canonicalName: "Eggwhite",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Eosinophils": {
    canonicalName: "Eosinophils",
    description: `Eosinophils have an important role in detoxification and the breakdown and removal of protein.`,
    increaseCauses: [
          "Intestinal parasites, SIBO (small intestinal bacterial overgrowth)",
          "Food sensitivity – gluten can be a sensitivity.  Gluten exacerbates gut dysfunction by disrupting the immune system located in the gut lining acting as a primary defense mechanism against pathogens entering our digestive tract. This is what leads to auto-immune disorders or gut dysbiosis.",
          "Environmental sensitivity – seasonal allergies"
    ],
    decreaseCauses: [
          "An eosinophil count at or below 1% or less is an uncommon finding and if present adrenal cortical hyperfunction should be ruled out."
    ],
    additionalProse: null,
  },
  "Estradiol (E2)": {
    canonicalName: "Estradiol (E2)",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Estriol (E3)": {
    canonicalName: "Estriol (E3)",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Estrogens": {
    canonicalName: "Estrogens",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Estrone (E1)": {
    canonicalName: "Estrone (E1)",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "FSH (Follicle Stimulating Hormone)": {
    canonicalName: "FSH (Follicle Stimulating Hormone)",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Ferritin": {
    canonicalName: "Ferritin",
    description: `Ferritin is the second most abundant iron-bearing protein in the body. It functions as an iron storage depot in the liver, spleen and bone marrow. 3 factors generally determine serum ferritin levels:`,
    increaseCauses: [
          "Iron overload/hemochromatosis",
          "Inflammatory disease",
          "Hepatitis",
          "HIV infection",
          "Cancer"
    ],
    decreaseCauses: [
          "Iron deficiency anemia"
    ],
    additionalProse: {
        bullets: [
          `the iron content of body tissues`,
          `the rate of ferritin dispersal from the tissues`,
          `the rate of ferritin extraction from the blood`,
        ],
      },
  },
  "GGT (Gamma-Glutamyl Transpeptidase)": {
    canonicalName: "GGT (Gamma-Glutamyl Transpeptidase)",
    description: `GGT is a more sensitive and specific indicator of liver dysfunction than ALP and in some conditions ALT. It is increased in all forms of liver/biliary dysfunction and is generally increased above ALT and AST with biliary tree problems (gall bladder, common bile duct, and pancreas) obstructive disease and alcoholism.`,
    increaseCauses: [
          "Biliary obstruction",
          "Alcoholism",
          "Bile duct and gall bladder inflammation/biliary insufficiency/biliary stasis",
          "Acute and chronic pancreatitis/pancreatic insufficiency"
    ],
    decreaseCauses: [
          "Vitamin B6 anemia: generally decreased below 10"
    ],
    additionalProse: null,
  },
  "Globulin": {
    canonicalName: "Globulin",
    description: `Total globulin is useful with other tests for assessing degenerative, inflammatory, and infectious processes and with BUN, serum phosphorus, serum gastrin, and other tests to confirm a need for HCL (hydrochloric acid).`,
    increaseCauses: [
          "Hypochlorhydria – lack of stomach acid",
          "Liver dysfunction/hepatic infections",
          "Neoplasm"
    ],
    decreaseCauses: [
          "Digestive dysfunction – lack of stomach acid"
    ],
    additionalProse: null,
  },
  "Glucose": {
    canonicalName: "Glucose",
    description: `Glucose levels are influenced by carbohydrate intake, stress, glandular and liver function.`,
    increaseCauses: [
          "Acute stress response",
          "Diabetes: triglycerides increased and often increased above the cholesterol level when a Type IV hyperlipoproteinemia is present (Metabolic Syndrome)",
          "Thiamine deficiency",
          "Dysinsulinism"
    ],
    decreaseCauses: [
          "Fasting hypoglycemia",
          "Severe liver disease",
          "Hypothyroidism"
    ],
    additionalProse: null,
  },
  "HDL (High Density Lipoprotein)": {
    canonicalName: "HDL (High Density Lipoprotein)",
    description: `HDL functions in the transport of cholesterol to the liver for metabolism to bile acids, hence it is though of as 'good' cholesterol. Within reason, if the cholesterol is high, but the HDL is also high and the LDL is normal, the patient is considered to be well protected.`,
    increaseCauses: [
          "Increased HDL cholesterol is generally not considered to be a pathological finding."
    ],
    decreaseCauses: [
          "Thyroid hyperfunction",
          "Diabetes",
          "Dysinsulinism (metabolic syndrome)"
    ],
    additionalProse: null,
  },
  "HDL Large": {
    canonicalName: "HDL Large",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [
          "Refers to the number of large mature HDL particles which are the most effective form of HDL for reverse cholesterol transport.  This is the movement of cholesterol out of the arteries and back to the liver.",
          "Low HDL indicates HDL dysfunction.",
          "This is most commonly seen with high ApoB and high LDL-P, which you have normal ApoB but high LDL-P; This will drive the systemic inflammation marker (hsCRP) into the average range where you are. Your presentation goes back to your gut health and the true reason your LDL-P is elevated is most likely due to gut dysbiosis."
    ],
    additionalProse: null,
  },
  "Hematocrit": {
    canonicalName: "Hematocrit",
    description: `Hematocrit is the total volume occupied by packed red blood cells when a given volume of whole blood is centrifuged.`,
    increaseCauses: [
          "Dehydration",
          "Hypoxia = lowered blood oxygen level",
          "Asthma",
          "Polycythemia = making too many red blood cells"
    ],
    decreaseCauses: [
          "Iron deficiency anemia",
          "Microscopic internal bleeding",
          "Digestive inflammation"
    ],
    additionalProse: null,
  },
  "Hemoglobin": {
    canonicalName: "Hemoglobin",
    description: `Hemoglobin is the major component of the red blood cell and functions in the transport of oxygen.`,
    increaseCauses: [
          "Dehydration",
          "Hypoxia = lowered blood oxygen level",
          "Asthma",
          "Polycythemia = making too many red blood cells"
    ],
    decreaseCauses: [
          "Iron deficiency anemia",
          "Microscopic internal bleeding due to digestive inflammation"
    ],
    additionalProse: null,
  },
  "Hemoglobin A1C": {
    canonicalName: "Hemoglobin A1C",
    description: `Glycated hemoglobin values are used to assess long-term glucose control in diabetes, especially in patients with insulin dependent diabetes whose urinary and fasting blood glucose levels vary significantly from day to day`,
    increaseCauses: [
          "Diabetes – metabolic syndrome",
          "without elevating fasting glucose and elevated triglyceride levels almost equal to total cholesterol, you are not a diabetic at all",
          "sugar metabolism is disrupted due to EBV impacting the liver and also B vitamins not being methylated efficiently to be shunted into sugar metabolism pathways which allow for sugar to be turned to energy.  If the sugar isn't turned to energy efficiently, it sits in the blood stream longer and raises this marker.",
          "Patients with splenectomy"
    ],
    decreaseCauses: [
          "Chronic blood loss",
          "Hemolytic anemia"
    ],
    additionalProse: null,
  },
  "Homocysteine": {
    canonicalName: "Homocysteine",
    description: ``,
    increaseCauses: [
          "B Vitamins help to maintain normalized homocysteine levels. If not absorbing B vitamins see elevation in homocysteine.",
          "Homocysteine tests are often elevated before B vitamins or folic acid show abnormal results.",
          "If individuals don't get enough B vitamins they can't convert homocysteine to forms that can be used by the body therefore creating an increase.",
          "Elevations are also seen in cardiovascular disease as well as increased risk for coronary artery disease, heart disease, and stroke."
    ],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Hs-CRP": {
    canonicalName: "Hs-CRP",
    description: `CRP is produced primarily by the liver during an acute inflammatory process or other disease. It rises rapidly, but nonspecifically in response to tissue injury and inflammation. CRP is an excellent test to monitor the efficacy of supplements or prescribed drugs on systemic inflammation or injury.`,
    increaseCauses: [
          "Viral and bacterial infection",
          "Non specific tissue inflammation or injury",
          "Coronary artery inflammation/atherosclerosis",
          "Rheumatoid arthritis"
    ],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Insulin": {
    canonicalName: "Insulin",
    description: `Insulin is a hormone produced by the pancreas and is the main transporter of glucose from the blood into cells.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: {
        bullets: [
          `High/Normal levels of insulin indicate early stages of insulin resistance and metabolic syndrome.`,
        ],
      },
  },
  "Iron": {
    canonicalName: "Iron",
    description: ``,
    increaseCauses: [
          "Hemochromatosis",
          "Hepatic dysfunction – lack of detoxification",
          "Iron overload"
    ],
    decreaseCauses: [
          "Chronic blood loss",
          "Iron deficiency anemia",
          "Menses",
          "Cancer",
          "Hepatic dysfunction",
          "Crohn's disease",
          "Celiac"
    ],
    additionalProse: null,
  },
  "LDH (Lactate-Dehydrogenase)": {
    canonicalName: "LDH (Lactate-Dehydrogenase)",
    description: `LDH is an enzyme that is found in almost all of the body's cells (as well as in bacteria) and is released from cells into the fluid portion of blood (serum or plasma) when cells are damaged or destroyed. Thus, the blood level of LD is a general indicator of tissue and cellular damage. The level of LD may also rise in other types of body fluids (e.g.,cerebrospinal fluid, pleural fluid, etc.) in the presence of certain diseases.
An elevated level of LD may be seen with:`,
    increaseCauses: [],
    decreaseCauses: [
          "LDH deficiency affects how the body breaks down sugar for use as energy in cells, particularly muscle cells.",
          "Very common with digestive dysfunction.",
          "You may also have low LDH levels if you’ve consumed a large amount of ascorbic acid (vitamin C)."
    ],
    additionalProse: {
        bullets: [
          `Hemolytic anemia`,
          `Pernicious anemia (vitamin B anemia)`,
          `Infections such as infectious mononucleosis (mono), meningitis, encephalitis, HIV`,
          `Sepsis`,
          `Intestinal and lung (pulmonary) infarction`,
          `Acute kidney disease`,
          `Acute liver disease`,
          `Acute muscle injury`,
          `Pancreatitis`,
          `Bone fractures`,
          `Testicular cancer, lymphoma or other cancers`,
        ],
      },
  },
  "LDL (Low Density Lipoprotein Cholesterol)": {
    canonicalName: "LDL (Low Density Lipoprotein Cholesterol)",
    description: `LDL is associated in the diagnosis of atherosclerosis, dysinsulinism, coronary artery disease and frank or developing diabetes.`,
    increaseCauses: [
          "Liver dysfunction due to lack of detoxification caused by EBV.",
          "Poor fat metabolism",
          "Metabolic syndrome/insulin resistance",
          "Cholesterol Ratio HDL/Total = >0.24 → no risk for cardiac event",
          "Cholesterol Ratio Triglyceride/HDL = <2 → no risk for cardiac event"
    ],
    decreaseCauses: [],
    additionalProse: null,
  },
  "LDL Medium": {
    canonicalName: "LDL Medium",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: {
        bullets: [
          `For the same reasons as above`,
        ],
      },
  },
  "LDL Particle": {
    canonicalName: "LDL Particle",
    description: `The number of LDL particles, not the cholesterol inside them.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: {
        bullets: [
          `LDL-P may be elevated for those with metabolic syndrome and insulin resistance.  You don’t have either of these conditions.`,
          `Your A1C is falsely elevated due to increased glycation.`,
          `Glucose gets stored in triglycerides, and then packaged into LDL particles. This means there may not be enough space left over for cholesterol, so the liver compensates by increasing LDL particle production.`,
          `We need to correct methylation and improve sugar metabolism and how your body handles sugar in the blood stream and this will decrease`,
          `Along those lines, metabolic syndrome is often associated with metabolic endotoxemia, always secondary to leaky gut syndrome. This process involves overgrowth of pathogenic gut flora which produce a toxin called LPS (lipopolysaccharides). LPS can get released into the bloodstream from a sufficiently inflamed gut. One of the mechanisms by which the body combats this is via a protein called the LPS-binding protein, which circulate along with the ApoB on the LDL-P. Therefore, in the presence of metabolic endotoxemia, the body will increase LDL-P production. The treatment in this case, of course, is to heal the gut so that the leakage ceases.`,
          `Your blood work does indicate digestive dysfunction that could lead to an overgrowth of bad bacteria in the gut.  There were not any markers tested to identify an imbalance in gut bacteria.  We are first going to correct digestion and remove any food triggers to decrease gut inflammation and the body can oftentimes correct itself if an overgrowth of bacteria exists.`,
        ],
      },
  },
  "LDL Pattern": {
    canonicalName: "LDL Pattern",
    description: `Measures whether LDL particles are large and buoyant (Pattern A) or small and dense (Pattern B).
Pattern A (larger particles):`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: {
        bullets: [
          `Less atherogenic`,
          `More atherogenic`,
        ],
        outro: `Pattern B (smaller particles):`,
      },
  },
  "LDL Peak Size": {
    canonicalName: "LDL Peak Size",
    description: `Indicates the presence of small dense LDL particles most commonly seen with insulin resistance.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "LDL Small": {
    canonicalName: "LDL Small",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: {
        bullets: [
          `Increased glycation (adding glucose onto hemoglobin) after eating a meal can elevate this marker`,
          `Proper methylation pathways are needed to ensure that sugars are utilized efficiently`,
          `Consumption of grains and sugars–Any food that fuels the liver’s conversion of sugars to triglycerides that yields increased VLDL (very low-density lipoproteins) in the blood leads to formation of small LDL particles.`,
          `Endotoxemia–i.e., the entry of microbial byproducts into the bloodstream from dysbiosis (imbalance of good and bad bacteria in the gut)`,
        ],
      },
  },
  "LH (Luteinizing Hormone)": {
    canonicalName: "LH (Luteinizing Hormone)",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "LP PLA2 Activity": {
    canonicalName: "LP PLA2 Activity",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Lead Venous": {
    canonicalName: "Lead Venous",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Leptin": {
    canonicalName: "Leptin",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Linoleic Acid": {
    canonicalName: "Linoleic Acid",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Lipase": {
    canonicalName: "Lipase",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Lipoprotein (a)": {
    canonicalName: "Lipoprotein (a)",
    description: `A genetically determined LDL-like particle with a clot-promoting protein attached.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Lymphocytes": {
    canonicalName: "Lymphocytes",
    description: `Lymphocytes help to destroy the toxic products of protein metabolism. They migrate to areas of inflammation in both early and late stages of the inflammatory process.`,
    increaseCauses: [
          "Chronic viral and bacterial infections",
          "Viral infection (mumps, rubella, mononucleosis)"
    ],
    decreaseCauses: [
          "Active viral and bacterial infections",
          "Leukemiaorimmunodeficiency disease",
          "Lupus",
          "Prednisone"
    ],
    additionalProse: null,
  },
  "MCH (Mean Corpuscular Hemoglobin)": {
    canonicalName: "MCH (Mean Corpuscular Hemoglobin)",
    description: `MCH indicates the weight of hemoglobin of a single red blood cell.`,
    increaseCauses: [
          "Vitamin B12/folic acid anemia"
    ],
    decreaseCauses: [
          "Iron anemia",
          "Internal bleeding",
          "Toxic effects of lead, aluminum, cadmium, and other toxic chemicals",
          "Vitamin B6 anemia"
    ],
    additionalProse: null,
  },
  "MCHC (Mean Corpuscular Hemoglobin Concentration)": {
    canonicalName: "MCHC (Mean Corpuscular Hemoglobin Concentration)",
    description: `MCHC indicates the average hemoglobin concentration per unit volume of packed red blood cells.`,
    increaseCauses: [
          "Vitamin B12/folic acid anemia",
          "Dehydration"
    ],
    decreaseCauses: [
          "Internal bleeding",
          "Toxic effects of lead, aluminum, cadmium and other toxic metals",
          "Vitamin B6 anemia"
    ],
    additionalProse: null,
  },
  "MCV (Mean Corpuscular Volume)": {
    canonicalName: "MCV (Mean Corpuscular Volume)",
    description: `MCV indicates the volume occupied by an average red blood cell. MCV increase along with an increase or decrease in the NCH is a significant finding for vitamin B12, folic acid, iron, copper, or vitamin B6 anemia. MCV and MCH should always be viewed together.`,
    increaseCauses: [
          "Vitamin B12/folic acid anemia",
          "Dehydration"
    ],
    decreaseCauses: [
          "Iron anemia",
          "Microscopic internal bleeding"
    ],
    additionalProse: null,
  },
  "MPV (Mean Platelet Volume)": {
    canonicalName: "MPV (Mean Platelet Volume)",
    description: `Platelets, also called thrombocytes, are tiny fragments of cells that are essential for normal blood clotting. They are formed from very large cells called megakaryocytes in the bone marrow and are released into the blood to circulate. The platelet count is a test that determines the number of platelets in a person's sample of blood.
A low platelet count, also called thrombocytopenia, and accompanying signs and symptoms may be caused by a number of conditions and factors. The causes typically fall into one of two general categories:`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: {
        bullets: [
          `Disorders in which the bone marrow cannot produce enough platelets`,
          `Conditions in which platelets are used up (consumed) or destroyed faster than normal`,
          `Examples of conditions causing a low platelet count include:`,
          `Idiopathic thrombocytopenia (ITP), also known as immune thrombocytopenic purpura, is the result of antibody production against platelets.`,
          `Viral infections such as mononucleosis, hepatitis, HIV or measles`,
          `Certain drugs, such as aspirin and ibuprofen, some antibiotics (including those containing sulfa), colchicine and indomethacin, H2-blocking agents, hydralazine, isoniazid, quinidine, thiazide diuretics, and tolbutamide, are just a few that have been associated with drug-induced decreased platelet counts.`,
          `Heparin-induced thrombocytopenia (HIT) results in low platelets when a person who is on or received heparin therapy develops an antibody. (For more on this, see the article on HIT Antibody)`,
          `Leukemia, lymphoma, or another cancer that has spread (metastasized) to the bone marrow—people with cancers often experience excessive bleeding due to a significantly decreased number of platelets. As the number of cancer cells increases in the bone marrow, normal bone marrow cells are crowded out, resulting in fewer platelet-producing cells.`,
          `Aplastic anemia—a condition in which the production of all blood cells is significantly reduced`,
          `Long-term bleeding problems (e.g., chronic bleeding from stomach ulcers)`,
          `Sepsis, especially that caused by a serious bacterial infection with Gram-negative bacteria`,
          `Cirrhosis`,
          `Autoimmune disorders, such as lupus, where the body's immune system produces antibodies that attack its own organs or tissues, causing increased destruction of platelets`,
          `Chemotherapy or radiation therapy, which may affect the bone marrow's ability to produce platelets`,
          `Platelet consumption may be observed in various diseases and conditions. For example, disseminated intravascular coagulation (DIC), thrombocytopenic purpura (TTP) and hemolytic uremic syndrome (HUS) can result in fewer circulating platelets in the blood.`,
          `Exposure to toxic chemicals, such as pesticides, arsenic, or benzene`,
          `If the platelet count falls below 20,000 per microliter, spontaneous bleeding may occur and is considered a life-threatening risk. A person with a very low count may be given platelets through a transfusion. See Blood and Blood Components in the Blood Banking article for more details.`,
          `Cancer, most commonly lung, gastrointestinal, ovarian, breast or lymphoma`,
          `Anemia, in particular iron-deficiency anemia and hemolytic anemia`,
          `Inflammatory conditions such as inflammatory bowel disease (IBD) or rheumatoid arthritis`,
          `Infectious diseases such as tuberculosis`,
          `If an individual has had their spleen removed surgically`,
          `Use of birth control pills (oral contraceptives)`,
          `Some conditions may cause a temporary (transitory) increased platelet count. These may include:`,
          `Recovery from significant blood loss such as from trauma or major surgery`,
          `After physical activity or exertion`,
          `Recovery from excess alcohol consumption and vitamin B12 and folate deficiency`,
          `Rarely, thrombocytosis is caused by a bone marrow disorder. An example is thrombocythemia, also called primary or essential thrombocythemia, a rare myeloproliferative disorder in which the bone marrow produces an extremely high number of platelets. Often there are no signs and symptoms and the condition is discovered when testing is done for a health check or for other reasons.`,
        ],
        outro: `A high platelet count may be referred to as thrombocytosis. This is usually the result of an existing condition (also called secondary or reactive thrombocytosis) such as:`,
      },
  },
  "MTHFR": {
    canonicalName: "MTHFR",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: [
      {
        intro: `Educational Information only:`,
        bullets: [
          `MTHFR = methylenetetrahydrofolate reductase is a folate dependent enzyme involved in remethylation of homocysteine to methionine`,
          `Genes C677T and A1298C.`,
          `Having this copy of this gene is associated with a reduction in the MTHFR enzyme activity leading to increased homocysteine particularly when associated with lower plasma folate.`,
          `Having a MTHFR mutation means that the enzyme that converts folic acid into it’s activated form (5-MTHF) acts sluggishly.`,
          `Methylation is required for many processes in the body, from breaking down histamine, serotonin and dopamine to turning DNA on and off. Consequently, having a defective methylation capability is associated with psychiatric illnesses, such as schizophrenia, depression and bipolar, as well as autoimmunity disorders, ADD, autism, spina bifida, Down’s syndrome, miscarriages, and cancer.`,
          `Defective methylation can come from not having the 5-MTHF or not having enough B12, so the disorders and symptoms associated with the MTHFR mutations often overlap with those due to B12 deficiency.`,
          `Both copies have been implicated in several neurological and psychiatric disorders`,
          `Having copies of this mutation have been shown to be risk factors for depression especially in older adults`,
          `This leads to increased levels of homocysteine and interferes with neurotransmitter synthesis pathways in serotonin, norepinephrine, and dopamine – which are folate dependent pathways`,
          `Hyperhomocysteinemia is an independent risk factor for coronary artery disease, acute myocardial infarction, peripheral arterial disease, stroke, and venous thromboembolism.`,
        ],
      },
      {
        intro: `Recommended Treatment for MTHFR Mutation:`,
        bullets: [
          `Eliminate gluten from your diet especially wheat`,
          `DO NOT Limit ingestion of folic acid and folic acid containing foods`,
          `Dark leafy greens, spinach, kale, collards, romaine lettuce`,
          `Asparagus`,
          `Broccoli`,
          `Citrus fruits, papaya, oranges, grapefruit, strawberries, raspberries`,
          `Beans, peas, lentils`,
          `Avocado`,
          `Okra`,
          `Brussels sprouts`,
          `Seeds and nuts`,
          `Cauliflower`,
          `Beets`,
          `Corn`,
          `Celery`,
          `Carrots`,
          `Squash`,
          `Avoid drugs that increase homocysteine levels such as nitric oxide in dentistry`,
          `Avoid antacids as they block the absorption of vitamin B12 and other nutrients`,
        ],
        outro: `As long as you are taking a methylated form of folate, you will be able to tolerate these foods in your diet.  You will have to take this specialized form of B vitamin for the rest of your life due to your bodies inability to absorb B vitamins unless they are methylated.`,
      },
    ],
  },
  "Magnesium": {
    canonicalName: "Magnesium",
    description: `Magnesium is an important element found in the arteries, heart, bone, muscles, nerves, and teeth.`,
    increaseCauses: [
          "Kidney Dysfunction",
          "Heart disease",
          "Excessive antacid use"
    ],
    decreaseCauses: [
          "Anxiety",
          "Muscle aches",
          "Irritability",
          "Insomnia",
          "Sensitivity to light/sound",
          "Epilepsy",
          "Disorientation"
    ],
    additionalProse: null,
  },
  "Magnesium RBC": {
    canonicalName: "Magnesium RBC",
    description: `Magnesium is an important element found in the arteries, heart, bone, muscles, nerves, and teeth.`,
    increaseCauses: [],
    decreaseCauses: [
          "Anxiety",
          "Muscle aches",
          "Irritability",
          "Insomnia",
          "Sensitivity to light/sound",
          "Disorientation"
    ],
    additionalProse: null,
  },
  "Mercury Blood": {
    canonicalName: "Mercury Blood",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Methylmalonic Acid": {
    canonicalName: "Methylmalonic Acid",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Monocytes": {
    canonicalName: "Monocytes",
    description: `Monocytes engulf some bacteria, particulate matter and protozoa. In the inflammatory process neutrophils predominate for about 3 days then they break up and the monocytes remain to phagocytize fragments of cells, etc. You often see an increase in the monocytes during the recovery phase of an infection.`,
    increaseCauses: [
          "Viral infections",
          "Important considerations with increased monocytes:",
          "always rule out liver dysfunction with increased monocytes",
          "increased monocytes indicate excessive tissue breakdown",
          "an increase in monocytes with an increase in basophils above (1.0) and even a mild increase in the eosinophils (above 3.0) is reason to suspect intestinal parasites",
          "the monocyte percentage will frequently increase with a decrease in the lymphocyte percentage with Hodgkin's disease and several other forms of cancer"
    ],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Neutrophils": {
    canonicalName: "Neutrophils",
    description: `Neutrophils have a chief function of phagocytosis (to engulf bacteria/virus)`,
    increaseCauses: [
          "Active viral or bacterial infection"
    ],
    decreaseCauses: [
          "Chronic viral or bacterial infection"
    ],
    additionalProse: null,
  },
  "Omega Check": {
    canonicalName: "Omega Check",
    description: `This test helps to bridge the gap between what you’re eating with omegas in them and what your body is able to use.  Having a low level indicates your body is not able to digest and utilize fats efficiently in the gut.
Eating quality wild caught fatty fish helps with heart and brain function.  We are going to help your body utilize fats more efficiently.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Omega-3 Total": {
    canonicalName: "Omega-3 Total",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Omega-6 Total": {
    canonicalName: "Omega-6 Total",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Omega-6/Omega-3 Ratio": {
    canonicalName: "Omega-6/Omega-3 Ratio",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "PSA % Free": {
    canonicalName: "PSA % Free",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "PSA Free": {
    canonicalName: "PSA Free",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "PSA Total": {
    canonicalName: "PSA Total",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Platelets": {
    canonicalName: "Platelets",
    description: `Platelets are involved with the clotting of blood coagulation, vasoconstriction and vascular integrity.`,
    increaseCauses: [
          "Rheumatoid arthritis",
          "Ateriosclerosis",
          "Some types of cancers",
          "Several types of anemia",
          "Polycythemia",
          "During pregnancy (slight increase)"
    ],
    decreaseCauses: [
          "Idiopathic thrombocytopenia",
          "Blood loss",
          "Thrombocytopenia"
    ],
    additionalProse: null,
  },
  "Potassium": {
    canonicalName: "Potassium",
    description: `Potassium is the major ion found inside the cells. Potassium is essential to maintenance of pH (blood and urine) and the maintenance of osmotic pressure. Potassium is also a determinant factor in maintaining membrane electrical potential which is important for neuromuscular tissue.`,
    increaseCauses: [
          "Adrenal cortical hypofunction",
          "Renal dysfunction"
    ],
    decreaseCauses: [
          "Diarrhea",
          "Adrenal cortical hyperfunction",
          "Drug diuretics"
    ],
    additionalProse: null,
  },
  "Pregnenolone": {
    canonicalName: "Pregnenolone",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Progesterone": {
    canonicalName: "Progesterone",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Prolactin": {
    canonicalName: "Prolactin",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "RBC (Red Blood Cell)": {
    canonicalName: "RBC (Red Blood Cell)",
    description: `RBCs are responsible for carrying oxygen from the lungs to body tissues and the transference of carbon dioxide from the tissues to the lungs.`,
    increaseCauses: [
          "Polycythemia = making too many red blood cells",
          "Respiratory distress/hypoxia = lowered blood oxygen level",
          "Upper end of red blood cell regeneration (every 120 days)"
    ],
    decreaseCauses: [
          "Iron anemia",
          "Vitamin B12, Vitamin B6 and/or folic acid anemia",
          "Liver and renal dysfunction",
          "Hemorrhage"
    ],
    additionalProse: null,
  },
  "RDW (Red Cell Distribution Width)": {
    canonicalName: "RDW (Red Cell Distribution Width)",
    description: `An RDW increase is primarily indicative of iron deficiency anemia, however, it can also be increased with Vitamin B12 and/or folate anemia.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Rheumatoid Factor": {
    canonicalName: "Rheumatoid Factor",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "SHBG (Sex Hormone Binding Globulin)": {
    canonicalName: "SHBG (Sex Hormone Binding Globulin)",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Sodium": {
    canonicalName: "Sodium",
    description: `Sodium is the most abundant ion found outside the cells. It is most important in fluid balance, acid-base balance and renal, cardiac and adrenal function. Its primary function in the body is to chemically maintain osmotic pressure and acid-base balance and to transmit nerve impulses. Aldosterone causes conservation of sodium. ADH (antidiuretic hormone) controls the reabsorption of water in the kidneys, affecting sodium levels by dilution and concentration.`,
    increaseCauses: [
          "Chronic renal dysfunction",
          "Dehydration",
          "Adrenal fatigue – cortisol dysregulation"
    ],
    decreaseCauses: [
          "Adrenal fatigue – cortisol dysregulation",
          "Diarrhea"
    ],
    additionalProse: null,
  },
  "Soy": {
    canonicalName: "Soy",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Specific Gravity": {
    canonicalName: "Specific Gravity",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "T3 Free": {
    canonicalName: "T3 Free",
    description: `T3 is a thyroid hormone produced mainly from peripheral conversion of thyroxine (T4). T3 has a higher biological activity than T4 and will bind to protein (thyroid binding globulin, transthyretin, and albumin) less efficiently than T4. T3 and T4 exist in the serum in both bound and free forms.
T3 and T4:`,
    increaseCauses: [
          "Primary hyperthyroidism (Grave's)",
          "Acute thyroiditis (Early Hashimoto's)"
    ],
    decreaseCauses: [
          "Hypothyroidism",
          "Hepatic disease",
          "Iodine insufficiency",
          "Cushing's disease"
    ],
    additionalProse: null,
  },
  "T3 Total": {
    canonicalName: "T3 Total",
    description: `T3 is a thyroid hormone produced mainly from peripheral conversion of thyroxine (T4). T3 has a higher biological activity than T4 and will bind to protein (thyroid binding globulin, transthyretin, and albumin) less efficiently than T4. T3 and T4 exist in the serum in both bound and free forms.
T3 and T4:`,
    increaseCauses: [
          "Primary hyperthyroidism (Grave's)",
          "Acute thyroiditis (Early Hashimoto's)"
    ],
    decreaseCauses: [
          "Hypothyroidism",
          "Hepatic disease",
          "Iodine insufficiency",
          "Cushing's disease"
    ],
    additionalProse: null,
  },
  "T4 Free": {
    canonicalName: "T4 Free",
    description: `T4 is the major hormone secreted by the thyroid gland. T4 secretion is stimulated by thyroid stimulating hormone (TSH). Free T4 is a very small portion of total thyroxine and is the metabolically active fraction.
T3 and T4:`,
    increaseCauses: [
          "Primary hyperthyroidism (Grave's)",
          "Acute thyroiditis (Early Hashimoto's)"
    ],
    decreaseCauses: [
          "Hypothyroidism",
          "Hepatic disease",
          "Iodine insufficiency",
          "Cushing's disease"
    ],
    additionalProse: null,
  },
  "T4 Total": {
    canonicalName: "T4 Total",
    description: `T4 is the major hormone secreted by the thyroid gland. T4 secretion is stimulated by thyroid stimulating hormone (TSH). Free T4 is a very small portion of total thyroxine and is the metabolically active fraction.
T3 and T4:`,
    increaseCauses: [
          "Primary hyperthyroidism (Grave's)",
          "Acute thyroiditis (Early Hashimoto's)"
    ],
    decreaseCauses: [
          "Hypothyroidism",
          "Hepatic disease",
          "Iodine insufficiency",
          "Cushing's disease"
    ],
    additionalProse: null,
  },
  "TIBC (Total Iron Binding Capacity)": {
    canonicalName: "TIBC (Total Iron Binding Capacity)",
    description: `TIBC is the measurement of all proteins available for binding iron.`,
    increaseCauses: [
          "Iron anemia"
    ],
    decreaseCauses: [
          "Inflammatory diseases",
          "Cirrhosis"
    ],
    additionalProse: null,
  },
  "Testosterone Bioavailable": {
    canonicalName: "Testosterone Bioavailable",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Testosterone Free": {
    canonicalName: "Testosterone Free",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Testosterone Total": {
    canonicalName: "Testosterone Total",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Thyroglobulin Antibodies": {
    canonicalName: "Thyroglobulin Antibodies",
    description: `A thyroglobulin antibody test, is typically ordered along with the thyroglobulin test. Thyroglobulin antibodies (also called thyroglobulin autoantibodies) are proteins produced by the body's immune system that attack thyroglobulin. These antibodies can develop at any time. When they are present, they bind to any thyroglobulin that may be present in the blood and interfere with the interpretation of the thyroglobulin test. Once they have developed, they will not go away and from that point forward will affect the usefulness of the thyroglobulin test.`,
    increaseCauses: [
          "Autoimmune thyroid dysfunction"
    ],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Thyroid Peroxidase": {
    canonicalName: "Thyroid Peroxidase",
    description: ``,
    increaseCauses: [
          "Autoimmune thyroid dysfunction"
    ],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Total Bilirubin": {
    canonicalName: "Total Bilirubin",
    description: `Bilirubin is the end product of hemoglobin breakdown by the spleen, liver, kupfer cells and the bone marrow.
Total bilirubin = a combination of direct and indirect bilirubin
Direct bilirubin = post-hepatic, water-soluble (conjugated)
Indirect bilirubin = pre-hepatic, water-insoluble (unconjugated)`,
    increaseCauses: [
          "Gallstones (biliary obstruction)",
          "Liver metastasis",
          "Extrahepatic duct obstruction",
          "Gilbert syndrome (congenital enzyme deficiency interrupting conjugation of bilirubin)",
          "Hepatitis",
          "Cirrhosis",
          "Hemolytic anemia"
    ],
    decreaseCauses: [
          "none significant"
    ],
    additionalProse: null,
  },
  "Total Protein": {
    canonicalName: "Total Protein",
    description: `Total protein is the combination of albumin and total globulin.`,
    increaseCauses: [
          "Digestive dysfunction – lack of stomach acid",
          "Dehydration"
    ],
    decreaseCauses: [
          "Protein malnutrition/amino acid need",
          "Digestive inflammation – lack of stomach acid"
    ],
    additionalProse: null,
  },
  "Triglycerides": {
    canonicalName: "Triglycerides",
    description: `Triglycerides travel in the blood with cholesterol. A patient who is correctly metabolizing their fats, proteins and carbohydrates will generally have about half as much triglyceride as cholesterol. Increased triglycerides in conjunction with decreased HDL cholesterol was a more significant indicator for coronary artery disease than high serum cholesterol alone.`,
    increaseCauses: [
          "Dysinsulinism (metabolic syndrome)",
          "Hypothyroidism"
    ],
    decreaseCauses: [
          "Thyroid hyperfunction",
          "Vegetarian diets",
          "Autoimmune phenomenon",
          "Genetic predisposition",
          "Cirrhosis of the liver",
          "Celiac disease/wheat intolerance"
    ],
    additionalProse: null,
  },
  "Uric Acid": {
    canonicalName: "Uric Acid",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Urine pH": {
    canonicalName: "Urine pH",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Vitamin B12": {
    canonicalName: "Vitamin B12",
    description: ``,
    increaseCauses: [
          "rare, could be from liver not functioning at its best",
          "you liver stores B12 and when not functioning optimally it can release B12 into the blood stream",
          "this level isn't extreme, we are going to watch it"
    ],
    decreaseCauses: [
          "Related to malabsorption due to MTHFR mutation",
          "Reported that between 5-10% of patients with values 200-400 may experience hematologic (blood) and neuropsychiatric (fatigue, brain fog) symptoms due to occult (hidden) B12 deficiency.",
          "<1% of patients with values >400 will have symptoms",
          "MTHFR also causes lack of detoxification of the liver, as does EBV and both affect the ability to absorb vitamin B12 in the liver"
    ],
    additionalProse: null,
  },
  "Vitamin B6": {
    canonicalName: "Vitamin B6",
    description: `B vitamins are water soluble vitamins and any not absorbed by the body should be excreted in your urine. When B vitamins are elevated in the blood it is due to imbalance of good and bad bacteria in your digestive tract. When you don't fully digest your food into absorbable nutrients due to a lack of stomach acid; undigested food moves from your stomach to your small intestine where bad bacteria live and feed off of that undigested food and they produce waste products that cause bloating and inflammation. One of their waste products are B vitamins. That's the only way a water soluble vitamin can be elevated in blood serum.`,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Vitamin D 1,25 (OH)2 Total": {
    canonicalName: "Vitamin D 1,25 (OH)2 Total",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Vitamin D 25-OH": {
    canonicalName: "Vitamin D 25-OH",
    description: `Vitamin D upregulates the immune response and down-regulates cell proliferation and inflammation.`,
    increaseCauses: [
          "Vitamin D toxicity"
    ],
    decreaseCauses: [
          "Rickets (children) osteomalacia (adults)",
          "Osteoporosis",
          "Diabetes mellitus",
          "Osteoarthritis",
          "Hypertension",
          "Cardiovascular disease",
          "Metabolic syndrome",
          "Depression",
          "Cancers of the breast, prostate, and colon",
          "Musculoskeletal pain",
          "Chronic low back pain",
          "Inflammation"
    ],
    additionalProse: null,
  },
  "Vitamin D2": {
    canonicalName: "Vitamin D2",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Vitamin D3": {
    canonicalName: "Vitamin D3",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "WBC (White Blood Cell)": {
    canonicalName: "WBC (White Blood Cell)",
    description: `The major function of the WBCs is the fight infection, react against foreign bodies or tissues, and defend the body by engulfing that foreign body or tissue.`,
    increaseCauses: [
          "Childhood diseases (measles, mumps, chicken pox, rubella, etc.)",
          "Acute viral or bacterial infection",
          "Steroid use",
          "Thyroid storm/ auto-immune thyroid dysfunction",
          "Intestinal parasites",
          "Some types of cancer",
          "Infectious mononucleosis",
          "Adrenal dysfunction",
          "Digestive inflammation can disrupt the immune system protection we have in our intestinal lining that acts as a primary defense against pathogens getting into our body via our digestive tract.  If this is not working, out system immune system has to battle everything. Food sensitivites can exacerbate this."
    ],
    decreaseCauses: [
          "Chronic viral or bacterial infection",
          "Autoimmune disorder",
          "Systemic Lupus Erythematosis",
          "Hepatitis",
          "Vitamin B12, Vitamin B6, and/or folic acid anemia",
          "Intestinal parasites (chronic)",
          "Rheumatoid arthritis",
          "Iron deficiency"
    ],
    additionalProse: null,
  },
  "Wheat": {
    canonicalName: "Wheat",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "Yeast": {
    canonicalName: "Yeast",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "eGFR": {
    canonicalName: "eGFR",
    description: ``,
    increaseCauses: [],
    decreaseCauses: [],
    additionalProse: null,
  },
  "sTSH (Serum Thyroid Stimulating Hormone)": {
    canonicalName: "sTSH (Serum Thyroid Stimulating Hormone)",
    description: ``,
    increaseCauses: [
          "Primary thyroid hypofunction",
          "Liver dysfunction",
          "Large doses of iodine",
          "HIV"
    ],
    decreaseCauses: [
          "Thyroid hyperfunction secondary to anterior pituitary hypofunction"
    ],
    additionalProse: null,
  },
};

export const GROUP_NARRATIVES: GroupNarrative[] = [
  {
    groupName: "Epstein-Barr",
    members: ["EBV Early Antigen IgG","EBV Viral Capsid IgM","EBV Viral Capsid IgG","EBV Nuclear AG IgG"],
    description: `Indicates reactivation of a previous infection
Epstein-Barr virus (EBV) – A member of the herpes family of viruses, EBV infects most people during some point of their lives. When infection occurs during adolescence or young adulthood, it causes infectious mononucleosis 35% to 50% of the time. Symptoms of infectious mononucleosis are fever, sore throat, swollen lymph glands and extreme fatigue. Rarely a swollen spleen or liver involvement may develop; even more rarely heart problems and central nervous system involvement occur. Transmission of EBV requires intimate contact with the saliva of an infected person.`,
    additionalProse: null,
  },
  {
    groupName: "T4",
    members: ["T4 Total","T4 Free"],
    description: `T4 is the major hormone secreted by the thyroid gland. T4 secretion is stimulated by thyroid stimulating hormone (TSH). Free T4 is a very small portion of total thyroxine and is the metabolically active fraction.
T3 and T4:`,
    additionalProse: null,
  },
  {
    groupName: "T3",
    members: ["T3 Total","T3 Free"],
    description: `T3 is a thyroid hormone produced mainly from peripheral conversion of thyroxine (T4). T3 has a higher biological activity than T4 and will bind to protein (thyroid binding globulin, transthyretin, and albumin) less efficiently than T4. T3 and T4 exist in the serum in both bound and free forms.
T3 and T4:`,
    additionalProse: null,
  },
];
