// AUTO-GENERATED from samples/templates/Copy of BW Evaluation Form - google doc.docx
// via scripts/parse-chart.ts → scripts/generate-ranges-ts.ts. Hand-edits are fine;
// re-running the generator will overwrite this file.
//
// canonicalName preserves the doctor's exact wording from her master chart
// (including the 'Apoliopoprotein B' typo). The Apolipoprotein B correct spelling
// is included as an alias.

export interface InterpretationBand {
  label: string;                          // e.g. "Negative", "Optimal", "Moderate", "High", "Equivocal", "Positive"
  min: number | null;
  max: number | null;
  severity: "normal" | "borderline" | "abnormal";
}

/** How the flagging engine should evaluate this marker. See lib/flagging/. */
export type FlagType =
  | "optimal_two_tier"   // optimal range exists; flag if value falls outside it
  | "lab_range_only"     // no optimal range; flag against labRange only
  | "three_tier_band"    // Optimal/Moderate/High bands (see interpretationBands)
  | "categorical";       // value is a string; match against expectedValue

export interface MarkerRange {
  canonicalName: string;
  aliases: string[];
  unit: string;
  labRange: { min: number | null; max: number | null };
  optimalRange: { min: number | null; max: number | null };
  optimalRangeBySex?: {
    male: { min: number | null; max: number | null };
    female: { min: number | null; max: number | null };
  };
  interpretationBands?: InterpretationBand[];     // 3-zone markers (e.g. EBV antibodies, cardiac panel)
  panelType?: "standard" | "food_sensitivity";    // marks variable per-patient panels
  requiresConfirmation?: boolean;                 // true = doctor must verify before tool uses range
  confirmationSource?: string | null;             // citation for proposed/derived ranges
  confirmationNotes?: string;                     // context for the doctor when reviewing
  flagType: FlagType;                             // drives the flagging engine
  expectedValue?: string;                         // categorical markers (e.g. "Negative", "A")
  bandDirection?: "higher_is_worse" | "higher_is_better"; // three_tier_band orientation
  cyclePhaseDependent?: boolean;                  // hormones — flagged against widest range in v1
  flaggedAboveCutoff?: boolean;                   // lab_range_only with single upper cutoff (e.g. EBV)
  category: string;
  increaseCauses: string[];
  decreaseCauses: string[];
  notes?: string | null;                          // optional context for edge cases
  /** @deprecated use `notes` instead. Kept for backward compatibility. */
  note?: string;
}

export const OPTIMAL_RANGES: Record<string, MarkerRange> = {
  rbc_red_blood_cell: {
    canonicalName: "RBC (Red Blood Cell)",
    aliases: [
      "Erythrocytes",
      "RBC",
      "RBC (RED BLOOD CELL)",
      "RBC (Red Blood Cell)",
      "RED BLOOD CELL",
      "Red Blood Cell",
      "Red Blood Cell Count",
      "rbc",
      "rbc (red blood cell)",
      "red blood cell",
    ],
    unit: "x10E6/uL",
    labRange: { min: 3.8, max: 5.1 },
    optimalRange: { min: 3.9, max: 5.6 },
    optimalRangeBySex: {
      male: { min: 4.1, max: 5.6 },
      female: { min: 3.9, max: 4.5 },
    },
    flagType: "optimal_two_tier",
    category: "hematology",
    increaseCauses: [
      "Polycythemia = making too many red blood cells",
      "Respiratory distress/hypoxia = lowered blood oxygen level",
      "Upper end of red blood cell regeneration (every 120 days)",
    ],
    decreaseCauses: [
      "Iron anemia",
      "Vitamin B12, Vitamin B6 and/or folic acid anemia",
      "Liver and renal dysfunction",
      "Hemorrhage",
    ],
  },
  hemoglobin: {
    canonicalName: "Hemoglobin",
    aliases: [
      "HEMOGLOBIN",
      "HGB",
      "Hemoglobin",
      "Hgb",
      "hemoglobin",
    ],
    unit: "g/dL",
    labRange: { min: 11.7, max: 15.5 },
    optimalRange: { min: 13.5, max: 15.5 },
    optimalRangeBySex: {
      male: { min: 14, max: 15.5 },
      female: { min: 13.5, max: 14.5 },
    },
    flagType: "optimal_two_tier",
    category: "hematology",
    increaseCauses: [
      "Dehydration",
      "Hypoxia = lowered blood oxygen level",
      "Asthma",
      "Polycythemia = making too many red blood cells",
    ],
    decreaseCauses: [
      "Iron deficiency anemia",
      "Microscopic internal bleeding due to digestive inflammation",
    ],
  },
  hematocrit: {
    canonicalName: "Hematocrit",
    aliases: [
      "HCT",
      "HEMATOCRIT",
      "Hct",
      "Hematocrit",
      "hematocrit",
    ],
    unit: "%",
    labRange: { min: 35, max: 45 },
    optimalRange: { min: 37, max: 48 },
    optimalRangeBySex: {
      male: { min: 40, max: 48 },
      female: { min: 37, max: 44 },
    },
    flagType: "optimal_two_tier",
    category: "hematology",
    increaseCauses: [
      "Dehydration",
      "Hypoxia = lowered blood oxygen level",
      "Asthma",
      "Polycythemia = making too many red blood cells",
    ],
    decreaseCauses: [
      "Iron deficiency anemia",
      "Microscopic internal bleeding",
      "Digestive inflammation",
    ],
  },
  mcv_mean_corpuscular_volume: {
    canonicalName: "MCV (Mean Corpuscular Volume)",
    aliases: [
      "MCV",
      "MCV (MEAN CORPUSCULAR VOLUME)",
      "MCV (Mean Corpuscular Volume)",
      "MEAN CORPUSCULAR VOLUME",
      "Mean Corpuscular Volume",
      "mcv",
      "mcv (mean corpuscular volume)",
      "mean corpuscular volume",
    ],
    unit: "fL",
    labRange: { min: 80, max: 100 },
    optimalRange: { min: 82, max: 89.9 },
    flagType: "optimal_two_tier",
    category: "hematology",
    increaseCauses: [
      "Vitamin B12/folic acid anemia",
      "Dehydration",
    ],
    decreaseCauses: [
      "Iron anemia",
      "Microscopic internal bleeding",
    ],
  },
  mch_mean_corpuscular_hemoglobin: {
    canonicalName: "MCH (Mean Corpuscular Hemoglobin)",
    aliases: [
      "MCH",
      "MCH (MEAN CORPUSCULAR HEMOGLOBIN)",
      "MCH (Mean Corpuscular Hemoglobin)",
      "MEAN CORPUSCULAR HEMOGLOBIN",
      "Mean Corpuscular Hemoglobin",
      "mch",
      "mch (mean corpuscular hemoglobin)",
      "mean corpuscular hemoglobin",
    ],
    unit: "pg",
    labRange: { min: 27, max: 33 },
    optimalRange: { min: 27, max: 31.9 },
    flagType: "optimal_two_tier",
    category: "hematology",
    increaseCauses: [
      "Vitamin B12/folic acid anemia",
    ],
    decreaseCauses: [
      "Iron anemia",
      "Internal bleeding",
      "Toxic effects fo lead, aluminum, cadmiun, and other toxic chemicals",
      "Vitamin B6 anemia",
    ],
  },
  mchc_mean_corpuscular_hemoglobin_concentration: {
    canonicalName: "MCHC (Mean Corpuscular Hemoglobin Concentration)",
    aliases: [
      "MCHC",
      "MCHC (MEAN CORPUSCULAR HEMOGLOBIN CONCENTRATION)",
      "MCHC (Mean Corpuscular Hemoglobin Concentration)",
      "MEAN CORPUSCULAR HEMOGLOBIN CONCENTRATION",
      "Mean Corpuscular Hemoglobin Concentration",
      "mchc",
      "mchc (mean corpuscular hemoglobin concentration)",
      "mean corpuscular hemoglobin concentration",
    ],
    unit: "g/dL",
    labRange: { min: 32, max: 36 },
    optimalRange: { min: 32, max: 36 },
    flagType: "optimal_two_tier",
    category: "hematology",
    increaseCauses: [
      "Vitamin B12/folic acid anemia",
      "Dehydration",
    ],
    decreaseCauses: [
      "Internal bleeding",
      "Toxic effects of lead, aluminum, cadmium and other toxic metals",
      "Vitamin B6 anemia",
    ],
  },
  rdw_red_cell_distribution_width: {
    canonicalName: "RDW (Red Cell Distribution Width)",
    aliases: [
      "RDW",
      "RDW (RED CELL DISTRIBUTION WIDTH)",
      "RDW (Red Cell Distribution Width)",
      "RDW-CV",
      "RDW-SD",
      "RED CELL DISTRIBUTION WIDTH",
      "Red Cell Distribution Width",
      "rdw",
      "rdw (red cell distribution width)",
      "red cell distribution width",
    ],
    unit: "%",
    labRange: { min: 11, max: 15 },
    optimalRange: { min: null, max: 13 },
    flagType: "optimal_two_tier",
    category: "hematology",
    increaseCauses: [],
    decreaseCauses: [],
  },
  platelets: {
    canonicalName: "Platelets",
    aliases: [
      "PLATELETS",
      "PLT",
      "Platelet Count",
      "Platelets",
      "platelets",
    ],
    unit: "x10E3/uL",
    labRange: { min: 140, max: 400 },
    optimalRange: { min: 140, max: 400 },
    flagType: "optimal_two_tier",
    category: "hematology",
    increaseCauses: [
      "Rheumatoid arthritis",
      "Ateriosclerosis",
      "Some types of cancers",
      "Several types of anemia",
      "Polycythemia",
      "During pregnancy (slight increase)",
    ],
    decreaseCauses: [
      "Idiopathic thromocytopenia",
      "Blood loss",
      "Thrombocytopenia",
    ],
  },
  mpv_mean_platelet_volume: {
    canonicalName: "MPV (Mean Platelet Volume)",
    aliases: [
      "MEAN PLATELET VOLUME",
      "MPV",
      "MPV (MEAN PLATELET VOLUME)",
      "MPV (Mean Platelet Volume)",
      "Mean Platelet Volume",
      "mean platelet volume",
      "mpv",
      "mpv (mean platelet volume)",
    ],
    unit: "fL",
    labRange: { min: 7.5, max: 12.5 },
    optimalRange: { min: 7.5, max: 11.5 },
    flagType: "optimal_two_tier",
    category: "hematology",
    increaseCauses: [],
    decreaseCauses: [],
  },
  wbc_white_blood_cell: {
    canonicalName: "WBC (White Blood Cell)",
    aliases: [
      "Leukocytes",
      "WBC",
      "WBC (WHITE BLOOD CELL)",
      "WBC (White Blood Cell)",
      "WHITE BLOOD CELL",
      "White Blood Cell",
      "White Blood Cell Count",
      "wbc",
      "wbc (white blood cell)",
      "white blood cell",
    ],
    unit: "x10E3/uL",
    labRange: { min: 3.8, max: 10 },
    optimalRange: { min: 5, max: 8 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [
      "Childhood diseases (measles, mumps, chicken pox, rubella, etc.)",
      "Acute viral or bacterial infection",
      "Steroid use",
      "Thyroid storm/ auto-immune thyroid dysfunction",
      "Intestinal parasites",
      "Some types of cancer",
      "Infectious mononucleosis",
      "Adrenal dysfunction",
      "Digestive inflammation can disrupt the immune system protection we have in our intestinal lining that acts as a primary defense against pathogens getting into our body via our digestive tract.  If this is not working, out system immune system has to battle everything. Food sensitivites can exacerbate this.",
    ],
    decreaseCauses: [
      "Chronic viral or bacterial infection",
      "Autoimmune disorder",
      "Systemic Lupus Erythematosis",
      "Hepatitis",
      "Vitamin B12, Vitamin B6, and/or folic acid anemia",
      "Intestinal parasites (chronic)",
      "Rheumatoid arthritis",
      "Iron deficiency",
    ],
  },
  neutrophils: {
    canonicalName: "Neutrophils",
    aliases: [
      "NEUTROPHILS",
      "Neut",
      "Neutrophil %",
      "Neutrophils",
      "Neutrophils %",
      "Neutrophils, Percent",
      "neutrophils",
    ],
    unit: "%",
    labRange: { min: 40, max: 74 },
    optimalRange: { min: 40, max: 60 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [
      "Active viral or bacterial infection",
    ],
    decreaseCauses: [
      "Chronic viral or bacterial infection",
    ],
  },
  lymphocytes: {
    canonicalName: "Lymphocytes",
    aliases: [
      "LYMPHOCYTES",
      "Lymph",
      "Lymph %",
      "Lymphocytes",
      "Lymphocytes %",
      "Lymphocytes, Percent",
      "lymphocytes",
    ],
    unit: "%",
    labRange: { min: 14, max: 46 },
    optimalRange: { min: 24, max: 44 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [
      "Chronic viral and bacterial infections",
      "Viral infection (mumps, rubella, mononucleosis)",
    ],
    decreaseCauses: [
      "Active viral and bacterial infections",
      "Leukemiaorimmunodeficiency disease",
      "Lupus",
      "Prednisone",
    ],
  },
  monocytes: {
    canonicalName: "Monocytes",
    aliases: [
      "MONOCYTES",
      "Mono",
      "Mono %",
      "Monocytes",
      "Monocytes %",
      "Monocytes, Percent",
      "monocytes",
    ],
    unit: "%",
    labRange: { min: 4, max: 13 },
    optimalRange: { min: 0, max: 7 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [
      "Viral infections",
      "always rule out liver dysfunction with increased monocytes",
      "increased monocytes indicate excessive tissue breakdown",
      "an increase in monocytes with an increase in basophils above (1.0) and even a mild increase in the eosinophils (above 3.0) is reason to suspect intestinal parasites",
      "the monocyte percentage will frequently increase with a decrease in the lymphocyte percentage with Hodkin's disease and several other forms of cancer",
    ],
    decreaseCauses: [],
  },
  eosinophils: {
    canonicalName: "Eosinophils",
    aliases: [
      "EOSINOPHILS",
      "Eos",
      "Eos %",
      "Eosinophils",
      "Eosinophils %",
      "Eosinophils, Percent",
      "eosinophils",
    ],
    unit: "%",
    labRange: { min: 0, max: 7 },
    optimalRange: { min: 0, max: 3 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [
      "Intestinal parasites, SIBO (small intestinal bacterial overgrowth)",
      "Food sensitivity – gluten can be a sensitivity.  Gluten exacerbates gut dysfunction by disrupting the immune system located in the gut lining acting as a primary defense mechanism against pathogens entering our digestive tract. This is what leads to auto-immune disorders or gut dysbiosis.",
      "Environmental sensitivity – seasonal allergies",
    ],
    decreaseCauses: [
      "An eosinphil count at or below 1% or less is an uncommon finding and if present adrenal cortical hyperfunction should be ruled out.",
    ],
  },
  basophils: {
    canonicalName: "Basophils",
    aliases: [
      "BASOPHILS",
      "Baso",
      "Baso %",
      "Basophils",
      "Basophils %",
      "Basophils, Percent",
      "basophils",
    ],
    unit: "%",
    labRange: { min: 0, max: 3 },
    optimalRange: { min: 0, max: 1 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [
      "Tissue inflammation",
      "Intestinal parasites",
      "Polycythemia",
    ],
    decreaseCauses: [
      "Stress",
      "Acute allergic reactions",
      "Hyperthyroidism",
      "Epstein-Barr",
    ],
  },
  ebv_early_antigen_igg: {
    canonicalName: "EBV Early Antigen IgG",
    aliases: [
      "EA IgG",
      "EBV EARLY ANTIGEN D AB (IGG)",
      "EBV Early Antigen D Ab (IgG)",
      "EBV EARLY ANTIGEN IGG",
      "EBV Early Antigen Ab IgG",
      "EBV Early Antigen IgG",
      "Early Antigen",
      "Early Antigen IgG",
      "ebv early antigen igg",
    ],
    unit: "U/mL",
    labRange: { min: null, max: 9 },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Negative", min: null, max: 9.0, severity: "normal" },
      { label: "Equivocal", min: 9.0, max: 10.99, severity: "borderline" },
      { label: "Positive", min: 10.99, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Quest Diagnostics reference cutoffs",
    flagType: "lab_range_only",
    flaggedAboveCutoff: true,
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
  },
  ebv_viral_capsid_igm: {
    canonicalName: "EBV Viral Capsid IgM",
    aliases: [
      "EBV VCA IgM",
      "EBV VIRAL CAPSID AG (VCA) AB (IGM)",
      "EBV Viral Capsid Ag (VCA) Ab (IgM)",
      "EBV VIRAL CAPSID IGM",
      "EBV Viral Capsid IgM",
      "VCA IgM",
      "Viral Capsid IgM",
      "ebv viral capsid igm",
    ],
    unit: "U/mL",
    labRange: { min: null, max: 36 },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Negative", min: null, max: 36.0, severity: "normal" },
      { label: "Equivocal", min: 36.0, max: 43.99, severity: "borderline" },
      { label: "Positive", min: 43.99, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Quest Diagnostics reference cutoffs",
    flagType: "lab_range_only",
    flaggedAboveCutoff: true,
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
  },
  ebv_viral_capsid_igg: {
    canonicalName: "EBV Viral Capsid IgG",
    aliases: [
      "EBV VCA IgG",
      "EBV VIRAL CAPSID AG (VCA) AB (IGG)",
      "EBV Viral Capsid Ag (VCA) Ab (IgG)",
      "EBV VIRAL CAPSID IGG",
      "EBV Viral Capsid IgG",
      "VCA IgG",
      "Viral Capsid IgG",
      "ebv viral capsid igg",
    ],
    unit: "U/mL",
    labRange: { min: null, max: 18 },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Negative", min: null, max: 18.0, severity: "normal" },
      { label: "Equivocal", min: 18.0, max: 21.99, severity: "borderline" },
      { label: "Positive", min: 21.99, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Quest Diagnostics reference cutoffs",
    flagType: "lab_range_only",
    flaggedAboveCutoff: true,
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
  },
  ebv_nuclear_ag_igg: {
    canonicalName: "EBV Nuclear AG IgG",
    aliases: [
      "EBNA",
      "EBNA IgG",
      "EBV NUCLEAR AG (EBNA) AB (IGG)",
      "EBV Nuclear Ag (EBNA) Ab (IgG)",
      "EBV NUCLEAR AG IGG",
      "EBV Nuclear AG IgG",
      "EBV Nuclear Antigen IgG",
      "Nuclear AG IgG",
      "Nuclear Antigen IgG",
      "ebv nuclear ag igg",
    ],
    unit: "U/mL",
    labRange: { min: null, max: 18 },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Negative", min: null, max: 18.0, severity: "normal" },
      { label: "Equivocal", min: 18.0, max: 21.99, severity: "borderline" },
      { label: "Positive", min: 21.99, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Quest Diagnostics reference cutoffs",
    flagType: "lab_range_only",
    flaggedAboveCutoff: true,
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
  },
  vitamin_d_25_oh: {
    canonicalName: "Vitamin D 25-OH",
    aliases: [
      "25(OH)D",
      "25-Hydroxyvitamin D",
      "25-OH Vitamin D",
      "VITAMIN D 25-OH",
      "VITAMIN D, 25-HYDROXY",
      "VITAMIN D,25-OH,TOTAL,IA",
      "Vit D 25-OH",
      "Vitamin D 25-OH",
      "Vitamin D, 25-Hydroxy",
      "Vitamin D,25-OH,Total,IA",
      "vitamin d 25-oh",
    ],
    unit: "ng/mL",
    labRange: { min: 30, max: 100 },
    optimalRange: { min: 40, max: 65 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [
      "Vitamin D toxicity",
    ],
    decreaseCauses: [
      "Rickets (children) osteomalacia (adults)",
      "Osteoporosis",
      "Diabetes mellitus",
      "Osteoarthritis",
      "Hypertension",
      "Cardiovascular disease",
      "Metabolic syndrome",
      "Depression",
      "Cancers of the breast, prostate, and colon",
      "Musculoskeletal pain",
      "Chronic low back pain",
      "Inflammation",
    ],
  },
  stsh_serum_thyroid_stimulating_hormone: {
    canonicalName: "sTSH (Serum Thyroid Stimulating Hormone)",
    aliases: [
      "SERUM THYROID STIMULATING HORMONE",
      "STSH",
      "STSH (SERUM THYROID STIMULATING HORMONE)",
      "Serum Thyroid Stimulating Hormone",
      "TSH",
      "TSH, 3rd Generation",
      "Thyroid Stimulating Hormone",
      "sTSH",
      "sTSH (Serum Thyroid Stimulating Hormone)",
      "serum thyroid stimulating hormone",
      "stsh",
      "stsh (serum thyroid stimulating hormone)",
    ],
    unit: "uIU/mL",
    labRange: { min: 0.4, max: 4.5 },
    optimalRange: { min: 1.5, max: 3 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [
      "Primary thyroid hypofunction",
      "Liver dysfunction",
      "Large doses of iodine",
      "HIV",
    ],
    decreaseCauses: [
      "Thyroid hyperfunction secondary to anterior pituitary hypofunction",
      "Serum Thyroxine (T4) Free and Total",
    ],
  },
  t4_free: {
    canonicalName: "T4 Free",
    aliases: [
      "FT4",
      "Free T4",
      "Free Thyroxine",
      "T4 FREE",
      "T4 Free",
      "T4, Free",
      "Thyroxine (T4), Free",
      "t4 free",
    ],
    unit: "ng/dL",
    labRange: { min: 0.8, max: 1.8 },
    optimalRange: { min: 0.8, max: 2.4 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
  },
  t4_total: {
    canonicalName: "T4 Total",
    aliases: [
      "T4 TOTAL",
      "T4 Total",
      "T4, Total",
      "Thyroxine",
      "Thyroxine (T4)",
      "Total T4",
      "t4 total",
    ],
    unit: "ug/dL",
    labRange: { min: 4.5, max: 12 },
    optimalRange: { min: 5, max: 12 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [
      "Primary hyperthyroidism (Grave's)",
      "Acute thyroiditis (Early Hashimoto's)",
    ],
    decreaseCauses: [
      "Hypothyroidism",
      "Hepatic disease",
      "Iodine insufficiency",
      "Cushing's disease",
      "Triiodothryonine (T3) Free and Total",
    ],
  },
  t3_free: {
    canonicalName: "T3 Free",
    aliases: [
      "FT3",
      "Free T3",
      "T3 FREE",
      "T3 Free",
      "T3, Free",
      "Triiodothyronine, Free",
      "t3 free",
    ],
    unit: "pg/mL",
    labRange: { min: 230, max: 420 },
    optimalRange: { min: 230, max: 420 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
  },
  t3_total: {
    canonicalName: "T3 Total",
    aliases: [
      "T3 TOTAL",
      "T3 Total",
      "T3, Total",
      "Total T3",
      "Triiodothyronine",
      "Triiodothyronine, Total",
      "t3 total",
    ],
    unit: "ng/dL",
    labRange: { min: 76, max: 181 },
    optimalRange: { min: 60, max: 181 },
    flagType: "optimal_two_tier",
    category: "immune_thyroid",
    increaseCauses: [
      "Primary hyperthyroidism (Grave's)",
      "Acute thyroiditis (Early Hashimoto's)",
    ],
    decreaseCauses: [
      "Hypothyroidism",
      "Hepatic disease",
      "Iodine insufficiency",
      "Cushing's disease",
    ],
  },
  thyroid_peroxidase: {
    canonicalName: "Thyroid Peroxidase",
    aliases: [
      "Anti-TPO",
      "THYROID PEROXIDASE",
      "TPO",
      "TPO Ab",
      "Thyroid Peroxidase",
      "Thyroid Peroxidase Antibodies",
      "thyroid peroxidase",
    ],
    unit: "IU/mL",
    labRange: { min: null, max: 9 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    category: "immune_thyroid",
    increaseCauses: [
      "Autoimmune thyroid dysfunction",
    ],
    decreaseCauses: [],
  },
  thyroglobulin_antibodies: {
    canonicalName: "Thyroglobulin Antibodies",
    aliases: [
      "Anti-Thyroglobulin",
      "THYROGLOBULIN ANTIBODIES",
      "TgAb",
      "Thyroglobulin Ab",
      "Thyroglobulin Antibodies",
      "thyroglobulin antibodies",
    ],
    unit: "IU/mL",
    labRange: { min: null, max: 1 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    category: "immune_thyroid",
    increaseCauses: [
      "Autoimmune thyroid dysfunction",
    ],
    decreaseCauses: [],
  },
  bun_blood_urea_nitrogen: {
    canonicalName: "BUN (Blood Urea Nitrogen)",
    aliases: [
      "BLOOD UREA NITROGEN",
      "BUN",
      "BUN (BLOOD UREA NITROGEN)",
      "BUN (Blood Urea Nitrogen)",
      "Blood Urea Nitrogen",
      "Urea Nitrogen",
      "blood urea nitrogen",
      "bun",
      "bun (blood urea nitrogen)",
    ],
    unit: "mg/dL",
    labRange: { min: 7, max: 25 },
    optimalRange: { min: 10, max: 15 },
    flagType: "optimal_two_tier",
    category: "kidney",
    increaseCauses: [
      "Chronic renal dysfunction",
      "Renal hypertension",
      "Prescribed diuretics",
      "Dehydration",
      "Liver stress",
      "Benin prostate hypertrophy – men",
      "Urinary obstruction",
    ],
    decreaseCauses: [
      "Liver failure/stress",
      "Protein malnutrition",
      "Celiac/wheat intolerance",
    ],
  },
  creatinine: {
    canonicalName: "Creatinine",
    aliases: [
      "CREATININE",
      "Creat",
      "Creatinine",
      "Serum Creatinine",
      "creatinine",
    ],
    unit: "mg/dL",
    labRange: { min: 0.5, max: 1.1 },
    optimalRange: { min: 0.8, max: 1.1 },
    flagType: "optimal_two_tier",
    category: "kidney",
    increaseCauses: [
      "Chronic renal dysfunction",
      "Benign prostate hypertrophy",
    ],
    decreaseCauses: [
      "Patients who have less than average muscle mass – due the liver being affected by EBV and not being able to generate protein properly",
    ],
  },
  bun_creatinine_ratio: {
    canonicalName: "BUN/Creatinine Ratio",
    aliases: [
      "BUN/CREATININE RATIO",
      "BUN/Creat Ratio",
      "BUN/Creatinine Ratio",
      "BUN:Creatinine",
      "bun/creatinine ratio",
    ],
    unit: "",
    labRange: { min: 6, max: 25 },
    optimalRange: { min: 10, max: 16 },
    flagType: "optimal_two_tier",
    category: "kidney",
    increaseCauses: [
      "Congestive heart failure",
      "Intestinal bleeding",
      "Shock",
      "Hypotension",
      "Dehydration",
      "Renal disease",
    ],
    decreaseCauses: [
      "Low protein diets",
      "Malnutrition",
    ],
  },
  ast_aspartate_aminotransferase: {
    canonicalName: "AST (Aspartate Aminotransferase)",
    aliases: [
      "ASPARTATE AMINOTRANSFERASE",
      "AST",
      "AST (ASPARTATE AMINOTRANSFERASE)",
      "AST (Aspartate Aminotransferase)",
      "Aspartate Aminotransferase",
      "SGOT",
      "aspartate aminotransferase",
      "ast",
      "ast (aspartate aminotransferase)",
    ],
    unit: "U/L",
    labRange: { min: 10, max: 30 },
    optimalRange: { min: 10, max: 30 },
    flagType: "optimal_two_tier",
    category: "liver",
    increaseCauses: [
      "Heart disease",
      "Liver disease",
      "Musculoskeletal",
      "Congestive heart failure",
      "Acute pancreatitis",
      "Liver dysfunction due to EBV disrupting detoxification and the liver compensating.",
    ],
    decreaseCauses: [
      "Vitamin B6 anemia",
      "Renal disease",
    ],
  },
  alt_alanine_aminotransferase: {
    canonicalName: "ALT (Alanine Aminotransferase)",
    aliases: [
      "ALANINE AMINOTRANSFERASE",
      "ALT",
      "ALT (ALANINE AMINOTRANSFERASE)",
      "ALT (Alanine Aminotransferase)",
      "Alanine Aminotransferase",
      "SGPT",
      "alanine aminotransferase",
      "alt",
      "alt (alanine aminotransferase)",
    ],
    unit: "U/L",
    labRange: { min: 6, max: 29 },
    optimalRange: { min: 10, max: 30 },
    flagType: "optimal_two_tier",
    category: "liver",
    increaseCauses: [
      "Cirrhosis of the liver",
      "Acute and chronic liver necrosis",
      "Hepatitis/mononucleosis",
      "Epstein-Barr virus and cytomegalovirus",
      "Acetaminophen",
    ],
    decreaseCauses: [
      "Vitamin B6 anemia",
    ],
  },
  alkaline_phosphatase: {
    canonicalName: "Alkaline Phosphatase",
    aliases: [
      "ALKALINE PHOSPHATASE",
      "ALP",
      "Alk Phos",
      "Alkaline Phosphatase",
      "alkaline phosphatase",
    ],
    unit: "U/L",
    labRange: { min: 31, max: 125 },
    optimalRange: { min: 70, max: 100 },
    flagType: "optimal_two_tier",
    category: "liver",
    increaseCauses: [
      "Healing fracture",
      "Liver cancer",
      "Cirrhosis",
      "Normal pregnancy (3rd trimester)",
      "Impairment of bile flow",
      "Paget's disease of bone",
    ],
    decreaseCauses: [
      "Biliary obstruction",
      "Zinc deficiency",
      "Vitamin C insufficiency",
    ],
  },
  total_bilirubin: {
    canonicalName: "Total Bilirubin",
    aliases: [
      "BILIRUBIN, TOTAL",
      "Bilirubin, Total",
      "TOTAL BILIRUBIN",
      "Tbili",
      "Total Bilirubin",
      "total bilirubin",
    ],
    unit: "mg/dL",
    labRange: { min: 0.2, max: 1.4 },
    optimalRange: { min: 0.2, max: 1.3 },
    flagType: "optimal_two_tier",
    category: "liver",
    increaseCauses: [],
    decreaseCauses: [
      "none significant",
    ],
  },
  total_protein: {
    canonicalName: "Total Protein",
    aliases: [
      "PROTEIN, TOTAL",
      "Protein, Total",
      "TOTAL PROTEIN",
      "TP",
      "Total Protein",
      "total protein",
    ],
    unit: "g/dL",
    labRange: { min: 6.1, max: 8.1 },
    optimalRange: { min: 6.6, max: 7.4 },
    flagType: "optimal_two_tier",
    category: "liver",
    increaseCauses: [
      "Digestive dysfunction – lack of stomach acid",
      "Dehydration",
    ],
    decreaseCauses: [
      "Protein malnutrition/amino acid need",
      "Digestive inflammation – lack of stomach acid",
    ],
  },
  albumin: {
    canonicalName: "Albumin",
    aliases: [
      "ALBUMIN",
      "Alb",
      "Albumin",
      "albumin",
    ],
    unit: "g/dL",
    labRange: { min: 3.6, max: 5.1 },
    optimalRange: { min: 4, max: 4.9 },
    flagType: "optimal_two_tier",
    category: "liver",
    increaseCauses: [
      "Dehydration",
    ],
    decreaseCauses: [
      "Liver/biliary dysfunction",
      "Neoplasm",
      "Protein malnutriton/amino acid need",
    ],
  },
  a_g_ratio: {
    canonicalName: "A/G Ratio",
    aliases: [
      "A/G RATIO",
      "A/G Ratio",
      "A:G Ratio",
      "Albumin/Globulin Ratio",
      "a/g ratio",
    ],
    unit: "",
    labRange: { min: 1, max: 2.5 },
    optimalRange: { min: 1.5, max: 2 },
    flagType: "optimal_two_tier",
    category: "liver",
    increaseCauses: [
      "not considered significant",
    ],
    decreaseCauses: [
      "Liver/biliary dysfunction",
      "Chronic renal disease",
      "Some types of cancer",
      "Sarcoidosis",
      "Collagen diseases",
      "Severe infections",
      "Systemic inflammation",
      "Burns",
      "Digestive inflammation",
    ],
  },
  globulin: {
    canonicalName: "Globulin",
    aliases: [
      "GLOBULIN",
      "Globulin",
      "Total Globulin",
      "globulin",
    ],
    unit: "g/dL",
    labRange: { min: 1.9, max: 3.7 },
    optimalRange: { min: 2.4, max: 2.8 },
    flagType: "optimal_two_tier",
    category: "liver",
    increaseCauses: [
      "Hypochlorhydria – lack of stomach acid",
      "Liver dysfunction/hepatic infections",
      "Neoplasm",
    ],
    decreaseCauses: [
      "Digestive dysfunction – lack of stomach acid",
    ],
  },
  ggt_gamma_glutamyl_transpeptidase: {
    canonicalName: "GGT (Gamma-Glutamyl Transpeptidase)",
    aliases: [
      "GAMMA-GLUTAMYL TRANSPEPTIDASE",
      "GGT",
      "GGT (GAMMA-GLUTAMYL TRANSPEPTIDASE)",
      "GGT (Gamma-Glutamyl Transpeptidase)",
      "Gamma GT",
      "Gamma-Glutamyl Transpeptidase",
      "Gamma-Glutamyltransferase",
      "gamma-glutamyl transpeptidase",
      "ggt",
      "ggt (gamma-glutamyl transpeptidase)",
    ],
    unit: "U/L",
    labRange: { min: 5, max: 35 },
    optimalRange: { min: 10, max: 30 },
    flagType: "optimal_two_tier",
    category: "liver",
    increaseCauses: [
      "Biliary obstruction",
      "Alcoholism",
      "Bile duct and gall bladder inflammation/biliary insufficiency/biliary stasis",
      "Acute and chronic pancreatitis/pancreatic insufficiency",
    ],
    decreaseCauses: [
      "Vitamin B6 anemia: generally decreased below 10",
    ],
  },
  cholesterol: {
    canonicalName: "Cholesterol",
    aliases: [
      "CHOLESTEROL",
      "CHOLESTEROL, TOTAL",
      "Chol",
      "Cholesterol",
      "Cholesterol, Total",
      "Total Cholesterol",
      "cholesterol",
    ],
    unit: "mg/dL",
    labRange: { min: 125, max: 200 },
    optimalRange: { min: 150, max: 220 },
    flagType: "optimal_two_tier",
    category: "lipid",
    increaseCauses: [
      "Coronary artery disease",
      "Diabetes",
      "Primary thyroid hypofunction or hypofunction secondary to anterior pituitary hypofunction.",
      "Liver dysfunction due to lack of detoxification caused by EBV.",
      "Poor fat metabolism",
    ],
    decreaseCauses: [
      "Thyroid hyperfunction and/or anterior pituitary hyperfunction",
      "Cancer",
      "Crohn's disease",
      "Cirrhosis of the liver",
      "Celiac disease",
      "Malnutrition",
    ],
  },
  ldl_low_density_lipoprotein_cholesterol: {
    canonicalName: "LDL (Low Density Lipoprotein Cholesterol)",
    aliases: [
      "LDL",
      "LDL (LOW DENSITY LIPOPROTEIN CHOLESTEROL)",
      "LDL (Low Density Lipoprotein Cholesterol)",
      "LDL Cholesterol",
      "LDL Cholesterol Calc",
      "LDL, Calculated",
      "LDL-C",
      "LOW DENSITY LIPOPROTEIN CHOLESTEROL",
      "Low Density Lipoprotein Cholesterol",
      "ldl",
      "ldl (low density lipoprotein cholesterol)",
      "low density lipoprotein cholesterol",
    ],
    unit: "mg/dL",
    labRange: { min: null, max: 100 },
    optimalRange: { min: null, max: 100 },
    flagType: "optimal_two_tier",
    category: "lipid",
    increaseCauses: [
      "Liver dysfunction due to lack of detoxification caused by EBV.",
      "Poor fat metabolism",
      "Metabolic syndrome/insulin resistance",
      "Cholesterol Ratio HDL/Total = >0.24 → no risk for cardiac event",
      "Cholesterol Ratio Triglyceride/HDL = <2 → no risk for cardiac event",
    ],
    decreaseCauses: [],
  },
  triglycerides: {
    canonicalName: "Triglycerides",
    aliases: [
      "TG",
      "TRIGLYCERIDES",
      "Trig",
      "Triglycerides",
      "triglycerides",
    ],
    unit: "mg/dL",
    labRange: { min: null, max: 150 },
    optimalRange: { min: 70, max: 100 },
    flagType: "optimal_two_tier",
    category: "lipid",
    increaseCauses: [
      "Dysinsulinism (metabolic syndrome)",
      "Hypothyroidism",
    ],
    decreaseCauses: [
      "Thyroid hyperfunction",
      "Vegetarian diets",
      "Autoimmune phenomenon",
      "Genetic predisposition",
      "Cirrhosis of the liver",
      "Celiac disease/wheat intolerance",
    ],
  },
  hdl_high_density_lipoprotein: {
    canonicalName: "HDL (High Density Lipoprotein)",
    aliases: [
      "HDL",
      "HDL (HIGH DENSITY LIPOPROTEIN)",
      "HDL (High Density Lipoprotein)",
      "HDL Cholesterol",
      "HDL-C",
      "HIGH DENSITY LIPOPROTEIN",
      "High Density Lipoprotein",
      "hdl",
      "hdl (high density lipoprotein)",
      "high density lipoprotein",
    ],
    unit: "mg/dL",
    labRange: { min: 50, max: null },
    optimalRange: { min: 50, max: 60 },
    flagType: "optimal_two_tier",
    category: "lipid",
    increaseCauses: [
      "Increased HDL cholesterol is generally not considered to be a pathological finding.",
    ],
    decreaseCauses: [
      "Thyroid hyperfunction",
      "Diabetes",
      "Dysinsulinism (metabolic syndrome)",
    ],
  },
  hemoglobin_a1c: {
    canonicalName: "Hemoglobin A1C",
    aliases: [
      "A1c",
      "Glycated Hemoglobin",
      "HEMOGLOBIN A1C",
      "HGBA1C",
      "HbA1c",
      "Hemoglobin A1C",
      "Hgb A1c",
      "hemoglobin a1c",
    ],
    unit: "%",
    labRange: { min: null, max: 5.7 },
    optimalRange: { min: null, max: 5 },
    flagType: "optimal_two_tier",
    category: "metabolic",
    increaseCauses: [
      "Diabetes – metbabolic syndrome",
      "without elevating fasting glucose and elevated triglyceride levels almost equal to total cholesterol, you are not a diabetic at all",
      "sugar metabolism is disrupted due to EBV impacting the liver and also B vitamins not being methylated efficiently to be shunted into sugar metabolism pathways which allow for sugar to be turned to energy.  If the sugar isn't turned to energy efficiently, it sits in the blood stream longer and raises this marker.",
      "Patients with spelenectomy",
    ],
    decreaseCauses: [
      "Chronic blood loss",
      "Hemolytic anemia",
    ],
  },
  glucose: {
    canonicalName: "Glucose",
    aliases: [
      "Blood Glucose",
      "FASTING GLUCOSE",
      "Fasting Glucose",
      "GLUCOSE",
      "Glucose",
      "Glucose (Fasting)",
      "Glucose, Fasting",
      "glucose",
    ],
    unit: "mg/dL",
    labRange: { min: 65, max: 99 },
    optimalRange: { min: 80, max: 95 },
    flagType: "optimal_two_tier",
    category: "metabolic",
    increaseCauses: [
      "Acute stress response",
      "Diabetes: triglycerides increased and often increased above the cholesterol level when a Type IV hyperlipoproteinemia is present (Metabolic Syndrome)",
      "Thiamine deficiency",
      "Dysinsulinism",
    ],
    decreaseCauses: [
      "Fasting hypoglycemia",
      "Severe liver disease",
      "Hypothyroidism",
    ],
  },
  insulin: {
    canonicalName: "Insulin",
    aliases: [
      "Fasting Insulin",
      "INSULIN",
      "Insulin",
      "insulin",
    ],
    unit: "uIU/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    category: "metabolic",
    increaseCauses: [],
    decreaseCauses: [],
  },
  hs_crp: {
    canonicalName: "Hs-CRP",
    aliases: [
      "C-Reactive Protein",
      "C-Reactive Protein, High Sensitivity",
      "CRP",
      "HS-CRP",
      "High Sensitivity CRP",
      "Hs-CRP",
      "hs-CRP",
      "hs-crp",
    ],
    unit: "mg/L",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Optimal", min: null, max: 1.0, severity: "normal" },
      { label: "Moderate", min: 1.0, max: 3.0, severity: "borderline" },
      { label: "High", min: 3.0, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Master chart (Carbone Chiropractic functional medicine report template)",
    flagType: "three_tier_band",
    bandDirection: "higher_is_worse",
    category: "cardio_iq",
    increaseCauses: [],
    decreaseCauses: [],
  },
  ldh_lactate_dehydrogenase: {
    canonicalName: "LDH (Lactate-Dehydrogenase)",
    aliases: [
      "LACTATE-DEHYDROGENASE",
      "LD",
      "LDH",
      "LDH (LACTATE-DEHYDROGENASE)",
      "LDH (Lactate-Dehydrogenase)",
      "Lactate Dehydrogenase",
      "Lactate-Dehydrogenase",
      "lactate-dehydrogenase",
      "ldh",
      "ldh (lactate-dehydrogenase)",
    ],
    unit: "U/L",
    labRange: { min: 100, max: 200 },
    optimalRange: { min: 140, max: 200 },
    flagType: "optimal_two_tier",
    category: "inflammation",
    increaseCauses: [],
    decreaseCauses: [
      "LDH deficiency affects how the body breaks down sugar for use as energy in cells, particularly muscle cells.",
      "Very common with digestive dysfunction.",
      "You may also have low LDH levels if you’ve consumed a large amount of ascorbic acid (vitamin C).",
    ],
  },
  calcium: {
    canonicalName: "Calcium",
    aliases: [
      "CALCIUM",
      "Ca",
      "Calcium",
      "calcium",
    ],
    unit: "mg/dL",
    labRange: { min: 8.6, max: 10.2 },
    optimalRange: { min: 9.4, max: 10 },
    flagType: "optimal_two_tier",
    category: "vitamins_minerals",
    increaseCauses: [
      "Parathyroid hyperfunction",
      "Cancer",
      "Hypervitaminosis D",
      "Sarcoidosis",
    ],
    decreaseCauses: [
      "Parathyroid hypofunction",
      "Digestive dysfunction (hypochlorhydria)",
      "Low/normal total protein or albumin",
      "Vitamin D insufficiency",
      "Protein malnutrition",
      "Osteoporosis",
      "Pancreatitis",
    ],
  },
  sodium: {
    canonicalName: "Sodium",
    aliases: [
      "Na",
      "SODIUM",
      "Sodium",
      "sodium",
    ],
    unit: "mmol/L",
    labRange: { min: 135, max: 146 },
    optimalRange: { min: 135, max: 142 },
    flagType: "optimal_two_tier",
    category: "vitamins_minerals",
    increaseCauses: [
      "Chronic renal dysfunction",
      "Dehydration",
      "Adrenal fatigue – cortisol dysregulation",
    ],
    decreaseCauses: [
      "Adrenal fatigue – cortisol dysregulation",
      "Diarrhea",
    ],
  },
  potassium: {
    canonicalName: "Potassium",
    aliases: [
      "K",
      "POTASSIUM",
      "Potassium",
      "potassium",
    ],
    unit: "mmol/L",
    labRange: { min: 3.5, max: 5.3 },
    optimalRange: { min: 4, max: 4.5 },
    flagType: "optimal_two_tier",
    category: "vitamins_minerals",
    increaseCauses: [
      "Adrenal cortical hypofunction",
      "Renal dysfunction",
    ],
    decreaseCauses: [
      "Diarrhea",
      "Adrenal cortical hyperfunction",
      "Drug diuretics",
    ],
  },
  chloride: {
    canonicalName: "Chloride",
    aliases: [
      "CHLORIDE",
      "Chloride",
      "Cl",
      "chloride",
    ],
    unit: "mmol/L",
    labRange: { min: 98, max: 110 },
    optimalRange: { min: 100, max: 106 },
    flagType: "optimal_two_tier",
    category: "vitamins_minerals",
    increaseCauses: [
      "Renal dysfunction",
      "Dehydration",
    ],
    decreaseCauses: [
      "Hypochlorhydria – lack of stomach acid",
    ],
  },
  co2_carbon_dioxide: {
    canonicalName: "CO2 (Carbon Dioxide)",
    aliases: [
      "Bicarbonate",
      "CARBON DIOXIDE",
      "CO2",
      "CO2 (CARBON DIOXIDE)",
      "CO2 (Carbon Dioxide)",
      "Carbon Dioxide",
      "HCO3",
      "carbon dioxide",
      "co2",
      "co2 (carbon dioxide)",
    ],
    unit: "mmol/L",
    labRange: { min: 20, max: 31 },
    optimalRange: { min: 26, max: 31 },
    flagType: "optimal_two_tier",
    category: "vitamins_minerals",
    increaseCauses: [
      "Metabolic alkalosis",
      "Vomiting",
    ],
    decreaseCauses: [
      "Thiamine deficiency, anion gap is generally increased",
      "Diabetes",
      "Metabolic acidosis – end product of food breakdown is more acidic",
    ],
  },
  magnesium: {
    canonicalName: "Magnesium",
    aliases: [
      "MAGNESIUM",
      "Magnesium",
      "Mg",
      "Mg, Serum",
      "magnesium",
    ],
    unit: "mg/dL",
    labRange: { min: 1.5, max: 2.5 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    category: "vitamins_minerals",
    increaseCauses: [
      "Kidney Dysfunction",
      "Heart disease",
      "Excessive antacid use",
    ],
    decreaseCauses: [
      "Anxiety",
      "Muscle aches",
      "Irritability",
      "Insomnia",
      "Sensitivity to light/sound",
      "Epilepsy",
      "Disorientation",
    ],
  },
  vitamin_b12: {
    canonicalName: "Vitamin B12",
    aliases: [
      "B12",
      "Cobalamin",
      "VITAMIN B12",
      "Vit B12",
      "Vitamin B12",
      "vitamin b12",
    ],
    unit: "pg/mL",
    labRange: { min: 200, max: 1100 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    category: "vitamins_minerals",
    increaseCauses: [
      "rare, could be from liver not functioning at it's best",
      "you liver stores B12 and when not functioning optimally it can release B12 into the blood stream",
      "this level isn't extreme, we are going to watch it",
    ],
    decreaseCauses: [
      "Related to malabsorption due to MTHFR mutation",
      "Reported that between 5-10% of patients with values 200-400 may experience hematologic (blood) and neuropsychiatric (fatigue, brain fog) symptoms due to occult (hidden) B12 deficiency.",
      "<1% of patients with values >400 will have symptoms",
      "MTHFR also causes lack of detoxification of the liver, as does EBV and both affect the ability to absorb vitamin B12 in the liver",
    ],
  },
  homocysteine: {
    canonicalName: "Homocysteine",
    aliases: [
      "HOMOCYSTEINE",
      "Homocyst(e)ine",
      "Homocysteine",
      "homocysteine",
    ],
    unit: "umol/L",
    labRange: { min: null, max: 10.4 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    category: "vitamins_minerals",
    increaseCauses: [
      "B Vitamins help to maintain normalized homocysteine levels. If not absorbing B vitamins see elevation in homocysteine.",
      "Homocysteine tests are often elevated before B vitamins or folic acid show abnormal results.",
      "If individuals don't get enough B vitamins they can't convert homocysteine to forms that can be used by the body therefore creating an increase.",
      "Elevations are also seen in cardiovascular disease as well as increased risk for coronary artery disease, heart disease, and stroke.",
    ],
    decreaseCauses: [],
  },
  iron: {
    canonicalName: "Iron",
    aliases: [
      "Fe",
      "IRON",
      "Iron",
      "Serum Iron",
      "iron",
    ],
    unit: "ug/dL",
    labRange: { min: 40, max: 190 },
    optimalRange: { min: 50, max: 100 },
    flagType: "optimal_two_tier",
    category: "iron",
    increaseCauses: [
      "Hemochromatosis",
      "Hepatic dysfunction – lack of detoxification",
      "Iron overload",
    ],
    decreaseCauses: [
      "Chronic blood loss",
      "Iron deficiency anemia",
      "Menses",
      "Cancer",
      "Hepatic dysfunction",
      "Crohn's disease",
      "Celiac",
    ],
  },
  ferritin: {
    canonicalName: "Ferritin",
    aliases: [
      "FERRITIN",
      "Ferritin",
      "ferritin",
    ],
    unit: "ng/mL",
    labRange: { min: 10, max: 154 },
    optimalRange: { min: 10, max: 200 },
    optimalRangeBySex: {
      male: { min: 20, max: 200 },
      female: { min: 10, max: 110 },
    },
    flagType: "optimal_two_tier",
    category: "iron",
    increaseCauses: [
      "Iron overload/hemochromatosis",
      "Inflammatory disease",
      "Hepatitis",
      "HIV infection",
      "Cancer",
    ],
    decreaseCauses: [
      "Iron deficiency anemia",
    ],
  },
  iron_saturation: {
    canonicalName: "% Iron Saturation",
    aliases: [
      "% IRON SATURATION",
      "% Iron Saturation",
      "% Saturation",
      "% iron saturation",
      "Iron Sat",
      "Iron Saturation",
      "Transferrin Saturation",
      "Tsat",
    ],
    unit: "%",
    labRange: { min: 11, max: 50 },
    optimalRange: { min: 20, max: 45 },
    flagType: "optimal_two_tier",
    category: "iron",
    increaseCauses: [],
    decreaseCauses: [],
  },
  tibc_total_iron_binding_capacity: {
    canonicalName: "TIBC (Total Iron Binding Capacity)",
    aliases: [
      "IRON BINDING CAPACITY",
      "Iron Binding Capacity",
      "TIBC",
      "TIBC (TOTAL IRON BINDING CAPACITY)",
      "TIBC (Total Iron Binding Capacity)",
      "TOTAL IRON BINDING CAPACITY",
      "Total Iron Binding Capacity",
      "tibc",
      "tibc (total iron binding capacity)",
      "total iron binding capacity",
    ],
    unit: "ug/dL",
    labRange: { min: 250, max: 450 },
    optimalRange: { min: 250, max: 350 },
    flagType: "optimal_two_tier",
    category: "iron",
    increaseCauses: [
      "Iron anemia",
    ],
    decreaseCauses: [
      "Inflammatory diseases",
      "Cirrhosis",
    ],
  },
  // Food sensitivity panel — variable marker set per patient.
  // All food sensitivities use the same threshold pattern: labRange.max = 2.0
  // Any food name with this threshold should be treated as a food sensitivity
  // marker. The parser should handle these generically rather than requiring
  // each food to be pre-defined. The doctor's full panel list is pending —
  // see RANGES_REVIEW.md.
  casein: {
    canonicalName: "Casein",
    aliases: [
      "CASEIN",
      "Casein",
      "Casein IgG",
      "casein",
    ],
    unit: "U/mL",
    labRange: { min: null, max: 2 },
    optimalRange: { min: null, max: null },
    panelType: "food_sensitivity",
    flagType: "lab_range_only",
    category: "gut",
    increaseCauses: [],
    decreaseCauses: [],
  },
  cacao: {
    canonicalName: "Cacao",
    aliases: [
      "CACAO",
      "Cacao",
      "Cacao IgG",
      "Cocoa",
      "Cocoa IgG",
      "cacao",
    ],
    unit: "U/mL",
    labRange: { min: null, max: 2 },
    optimalRange: { min: null, max: null },
    panelType: "food_sensitivity",
    flagType: "lab_range_only",
    category: "gut",
    increaseCauses: [],
    decreaseCauses: [],
  },
  corn: {
    canonicalName: "Corn",
    aliases: [
      "CORN",
      "Corn",
      "Corn IgG",
      "corn",
    ],
    unit: "U/mL",
    labRange: { min: null, max: 2 },
    optimalRange: { min: null, max: null },
    panelType: "food_sensitivity",
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, confirmed via email 2026-05-31",
    category: "gut",
    increaseCauses: [],
    decreaseCauses: [],
  },
  eggwhite: {
    canonicalName: "Eggwhite",
    aliases: [
      "EGGWHITE",
      "Egg White",
      "Egg White IgG",
      "Eggwhite",
      "Eggwhite IgG",
      "eggwhite",
    ],
    unit: "U/mL",
    labRange: { min: null, max: 2 },
    optimalRange: { min: null, max: null },
    panelType: "food_sensitivity",
    flagType: "lab_range_only",
    category: "gut",
    increaseCauses: [],
    decreaseCauses: [],
  },
  wheat: {
    canonicalName: "Wheat",
    aliases: [
      "WHEAT",
      "Wheat",
      "Wheat IgG",
      "wheat",
    ],
    unit: "U/mL",
    labRange: { min: null, max: 2 },
    optimalRange: { min: null, max: null },
    panelType: "food_sensitivity",
    flagType: "lab_range_only",
    category: "gut",
    increaseCauses: [],
    decreaseCauses: [],
  },
  yeast: {
    canonicalName: "Yeast",
    aliases: [
      "Brewers Yeast",
      "YEAST",
      "Yeast",
      "Yeast IgG",
      "yeast",
    ],
    unit: "U/mL",
    labRange: { min: null, max: 2 },
    optimalRange: { min: null, max: null },
    panelType: "food_sensitivity",
    flagType: "lab_range_only",
    category: "gut",
    increaseCauses: [],
    decreaseCauses: [],
  },
  vitamin_b6: {
    canonicalName: "Vitamin B6",
    aliases: [
      "B6",
      "P5P",
      "Pyridoxal 5-Phosphate",
      "Pyridoxine",
      "VITAMIN B6",
      "Vitamin B6",
      "vitamin b6",
    ],
    unit: "ng/mL",
    labRange: { min: 2.1, max: 21.7 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    category: "gut",
    increaseCauses: [],
    decreaseCauses: [],
  },
  candida_albicans: {
    canonicalName: "Candida Albicans",
    aliases: [
      "CANDIDA ALBICANS",
      "Candida Albicans",
      "Candida Albicans Ab",
      "Candida IgG",
      "candida albicans",
    ],
    unit: "",
    labRange: { min: null, max: 1 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    category: "gut",
    increaseCauses: [],
    decreaseCauses: [],
  },
  ldl_particle: {
    canonicalName: "LDL Particle",
    aliases: [
      "LDL PARTICLE",
      "LDL Particle",
      "LDL Particle Number",
      "LDL Particles",
      "LDL-P",
      "ldl particle",
    ],
    unit: "nmol/L",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Optimal", min: null, max: 1138, severity: "normal" },
      { label: "Moderate", min: 1138, max: 1409, severity: "borderline" },
      { label: "High", min: 1409, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Master chart (Carbone Chiropractic functional medicine report template)",
    flagType: "three_tier_band",
    bandDirection: "higher_is_worse",
    category: "cardio_iq",
    increaseCauses: [],
    decreaseCauses: [],
  },
  ldl_small: {
    canonicalName: "LDL Small",
    aliases: [
      "LDL SMALL",
      "LDL Small",
      "Small LDL",
      "Small LDL Particle",
      "ldl small",
      "sdLDL",
    ],
    unit: "nmol/L",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Optimal", min: null, max: 142, severity: "normal" },
      { label: "Moderate", min: 142, max: 219, severity: "borderline" },
      { label: "High", min: 219, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Master chart (Carbone Chiropractic functional medicine report template)",
    flagType: "three_tier_band",
    bandDirection: "higher_is_worse",
    category: "cardio_iq",
    increaseCauses: [],
    decreaseCauses: [],
  },
  ldl_medium: {
    canonicalName: "LDL Medium",
    aliases: [
      "LDL MEDIUM",
      "LDL Medium",
      "Medium LDL",
      "ldl medium",
    ],
    unit: "nmol/L",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Optimal", min: null, max: 215, severity: "normal" },
      { label: "Moderate", min: 215, max: 301, severity: "borderline" },
      { label: "High", min: 301, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Master chart (Carbone Chiropractic functional medicine report template)",
    flagType: "three_tier_band",
    bandDirection: "higher_is_worse",
    category: "cardio_iq",
    increaseCauses: [],
    decreaseCauses: [],
  },
  hdl_large: {
    canonicalName: "HDL Large",
    aliases: [
      "HDL LARGE",
      "HDL Large",
      "HDL Large Particle",
      "Large HDL",
      "hdl large",
    ],
    unit: "umol/L",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    // NOTE: inverted scale — higher values are healthier. Bands ordered by min ascending.
    interpretationBands: [
      { label: "High", min: null, max: 5353, severity: "abnormal" },
      { label: "Moderate", min: 5353, max: 6729, severity: "borderline" },
      { label: "Optimal", min: 6729, max: null, severity: "normal" },
    ],
    confirmationSource: "Master chart (Carbone Chiropractic functional medicine report template)",
    flagType: "three_tier_band",
    bandDirection: "higher_is_better",
    category: "cardio_iq",
    increaseCauses: [],
    decreaseCauses: [],
  },
  ldl_pattern: {
    canonicalName: "LDL Pattern",
    aliases: [
      "LDL PATTERN",
      "LDL Pattern",
      "LDL Pattern A/B",
      "Lipoprotein Pattern",
      "ldl pattern",
    ],
    unit: "",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    // Categorical marker — flagging is done on string value, not numeric bands.
    confirmationSource: "Master chart (Carbone Chiropractic functional medicine report template)",
    flagType: "categorical",
    expectedValue: "A",
    category: "cardio_iq",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Categorical marker: Pattern A = Optimal, Pattern B = High risk. Flag as abnormal if value is 'B'.",
  },
  ldl_peak_size: {
    canonicalName: "LDL Peak Size",
    aliases: [
      "LDL PEAK SIZE",
      "LDL Particle Size",
      "LDL Peak Size",
      "LDL Size",
      "ldl peak size",
    ],
    unit: "Å",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    // NOTE: inverted scale — higher values are healthier. Bands ordered by min ascending.
    interpretationBands: [
      { label: "High", min: null, max: 217.4, severity: "abnormal" },
      { label: "Moderate", min: 217.4, max: 222.9, severity: "borderline" },
      { label: "Optimal", min: 222.9, max: null, severity: "normal" },
    ],
    confirmationSource: "Master chart (Carbone Chiropractic functional medicine report template)",
    flagType: "three_tier_band",
    bandDirection: "higher_is_better",
    category: "cardio_iq",
    increaseCauses: [],
    decreaseCauses: [],
  },
  apoliopoprotein_b: {
    canonicalName: "Apoliopoprotein B",
    aliases: [
      "APOLIOPOPROTEIN B",
      "Apo B",
      "ApoB",
      "Apoliopoprotein B",
      "Apolipoprotein B",
      "apoliopoprotein b",
    ],
    unit: "mg/dL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Optimal", min: null, max: 90, severity: "normal" },
      { label: "Moderate", min: 90, max: 120, severity: "borderline" },
      { label: "High", min: 120, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Master chart (Carbone Chiropractic functional medicine report template)",
    flagType: "three_tier_band",
    bandDirection: "higher_is_worse",
    category: "cardio_iq",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Chart's exact Moderate band is 90-119 (integer); High threshold is >=120. Modeled here with Moderate.max=120 / High.min=120 so the bands are contiguous.",
  },
  lipoprotein_a: {
    canonicalName: "Lipoprotein (a)",
    aliases: [
      "LIPOPROTEIN (A)",
      "Lipoprotein (a)",
      "Lipoprotein a",
      "Lipoprotein(a)",
      "Lp(a)",
      "lipoprotein (a)",
    ],
    unit: "nmol/L",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Optimal", min: null, max: 75, severity: "normal" },
      { label: "Moderate", min: 75, max: 125, severity: "borderline" },
      { label: "High", min: 125, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Master chart (Carbone Chiropractic functional medicine report template)",
    flagType: "three_tier_band",
    bandDirection: "higher_is_worse",
    category: "cardio_iq",
    increaseCauses: [],
    decreaseCauses: [],
  },
  lp_pla2_activity: {
    canonicalName: "LP PLA2 Activity",
    aliases: [
      "LP PLA2 ACTIVITY",
      "LP PLA2 Activity",
      "Lp-PLA2",
      "Lp-PLA2 Activity",
      "PLAC Test",
      "lp pla2 activity",
    ],
    unit: "nmol/min/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "Optimal", min: null, max: 123, severity: "normal" },
      { label: "High", min: 123, max: null, severity: "abnormal" },
    ],
    confirmationSource: "Master chart (Carbone Chiropractic functional medicine report template)",
    flagType: "three_tier_band",
    bandDirection: "higher_is_worse",
    category: "cardio_iq",
    increaseCauses: [],
    decreaseCauses: [],
  },

  // ----- Markers proposed for doctor confirmation -----
  // These markers are not in the master chart but commonly appear on the
  // patient panels we'll be parsing. Each is added with requiresConfirmation:
  // true so the flagging engine refuses to use them until the doctor supplies
  // ranges. Ranges are intentionally null — see RANGES_REVIEW.md.
  ana_antinuclear_antibodies: {
    canonicalName: "ANA (Anti-nuclear Antibodies)",
    aliases: [
      "ANA",
      "ANA (Anti-nuclear Antibodies)",
      "ANA Screen",
      "ANA Screen, IFA",
      "ANA Reflex Titer",
      "ANA, IFA",
      "ANA Direct",
      "ANTI-NUCLEAR ANTIBODIES",
      "ANTINUCLEAR ANTIBODY",
      "Antinuclear Antibody",
      "Antinuclear Antibodies",
      "Anti-Nuclear Antibody",
      "Anti-Nuclear Antibodies",
      "ana",
    ],
    unit: "",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "categorical",
    expectedValue: "Negative",
    confirmationSource: "Melissa Carbone, clinical experience, email 2026-05-27",
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Flag as out_of_range when reported result is anything other than 'Negative'. Titer/pattern are reported separately by labs but not used for flagging in v1.",
  },
  uric_acid: {
    canonicalName: "Uric Acid",
    aliases: [
      "URIC ACID",
      "Uric Acid",
      "Uric Acid, Serum",
      "Urate",
      "uric acid",
    ],
    unit: "mg/dL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, clinical experience, email 2026-05-27",
    category: "metabolic",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: flag against the lab-supplied reference range printed on each report — no fixed optimal range.",
  },
  cortisol: {
    canonicalName: "Cortisol",
    aliases: [
      "CORTISOL",
      "Cortisol",
      "Cortisol AM",
      "Cortisol PM",
      "Cortisol, Total",
      "Cortisol, Free",
      "Cortisol, Serum",
      "Cortisol, AM",
      "Cortisol, PM",
      "Serum Cortisol",
      "Salivary Cortisol",
      "Free Cortisol",
      "cortisol",
    ],
    unit: "ug/dL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, clinical experience, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: flag against the lab-supplied range printed on each report; ranges vary by collection method/time of day.",
  },
  estrogens: {
    canonicalName: "Estrogens",
    aliases: [
      "ESTROGENS",
      "Estrogens",
      "Total Estrogens",
      "Estrogen",
      "estrogens",
    ],
    unit: "pg/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    cyclePhaseDependent: true,
    confirmationSource: "Melissa Carbone, clinical experience, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: flag against the lab-supplied range printed on each report. Estradiol/Estrone/Estriol now tracked as separate markers (estradiol, estrone, estriol).",
  },

  // ===== Markers added 2026-05-27 from Melissa's tracking form =====
  // All ranges below are from Melissa's tracking-form template, sent via email
  // 2026-05-27 with subject "Re: review". Where ranges weren't supplied (vitamin
  // D variants, omega panel), the marker is encoded with labRange:null and
  // flagged as `not_flaggable` at runtime — the report still surfaces the value
  // for the clinician.

  // ----- Sex hormones (lab_range_only per Melissa) -----
  testosterone_total: {
    canonicalName: "Testosterone Total",
    aliases: [
      "TESTOSTERONE",
      "TESTOSTERONE, TOTAL",
      "TESTOSTERONE,TOTAL,MS",
      "Testosterone",
      "Testosterone Total",
      "Testosterone, Total",
      "Total Testosterone",
      "testosterone total",
    ],
    unit: "ng/dL",
    labRange: { min: 2, max: 45 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
  },
  testosterone_free: {
    canonicalName: "Testosterone Free",
    aliases: [
      "FREE TESTOSTERONE",
      "Free Testosterone",
      "TESTOSTERONE, FREE",
      "Testosterone Free",
      "Testosterone, Free",
      "testosterone free",
    ],
    unit: "pg/mL",
    labRange: { min: 0.2, max: 5.0 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
  },
  testosterone_bioavailable: {
    canonicalName: "Testosterone Bioavailable",
    aliases: [
      "BIOAVAILABLE TESTOSTERONE",
      "Bioavailable Testosterone",
      "TESTOSTERONE, BIOAVAILABLE",
      "TESTOSTERONE,BIOAVAILABLE",
      "Testosterone Bioavailable",
      "Testosterone, Bioavailable",
      "testosterone bioavailable",
    ],
    unit: "ng/dL",
    labRange: { min: 0.5, max: 8.5 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
  },
  shbg: {
    canonicalName: "SHBG (Sex Hormone Binding Globulin)",
    aliases: [
      "SHBG",
      "SEX HORMONE BINDING GLOBULIN",
      "Sex Hormone Binding Globulin",
      "shbg",
    ],
    unit: "nmol/L",
    labRange: { min: 17, max: 124 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
  },
  dhea_sulfate: {
    canonicalName: "DHEA Sulfate",
    aliases: [
      "DHEA",
      "DHEA SULFATE",
      "DHEA-S",
      "DHEA Sulfate",
      "DHEAS",
      "Dehydroepiandrosterone Sulfate",
      "dhea sulfate",
    ],
    unit: "ug/dL",
    labRange: { min: 14, max: 349 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
  },
  prolactin: {
    canonicalName: "Prolactin",
    aliases: [
      "PROLACTIN",
      "Prolactin",
      "prolactin",
    ],
    unit: "ng/mL",
    labRange: { min: 2, max: 30 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: range is 3-30 ng/mL for non-pregnant women, 2-20 ng/mL post-menopausal. v1 uses the widest combined range (2-30) — clinical interpretation required.",
  },
  progesterone: {
    canonicalName: "Progesterone",
    aliases: [
      "PROGESTERONE",
      "Progesterone",
      "progesterone",
    ],
    unit: "ng/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    cyclePhaseDependent: true,
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Cycle-phase dependent: follicular <1.0, ovulatory varies, luteal 2-25 ng/mL, post-menopausal <0.5. v1 flags only when the lab-supplied range is present on the report.",
  },
  pregnenolone: {
    canonicalName: "Pregnenolone",
    aliases: [
      "PREGNENOLONE",
      "PREGNENOLONE, MS",
      "Pregnenolone",
      "pregnenolone",
    ],
    unit: "ng/dL",
    labRange: { min: 22, max: 237 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
  },
  fsh: {
    canonicalName: "FSH (Follicle Stimulating Hormone)",
    aliases: [
      "FOLLICLE STIMULATING HORMONE",
      "FSH",
      "Follicle Stimulating Hormone",
      "fsh",
    ],
    unit: "mIU/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    cyclePhaseDependent: true,
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Cycle-phase dependent. v1 flags only when the lab-supplied range is present on the report; clinical interpretation required.",
  },
  lh: {
    canonicalName: "LH (Luteinizing Hormone)",
    aliases: [
      "LH",
      "LUTEINIZING HORMONE",
      "Luteinizing Hormone",
      "lh",
    ],
    unit: "mIU/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    cyclePhaseDependent: true,
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Cycle-phase dependent. v1 flags only when the lab-supplied range is present on the report; clinical interpretation required.",
  },
  amh: {
    canonicalName: "AMH (Anti-Mullerian Hormone)",
    aliases: [
      "AMH",
      "ANTI-MULLERIAN HORMONE",
      "ANTI-MULLERIAN HORMONE (AMH)",
      "ANTI-MULLERIAN HORMONE (AMH), FEMALE",
      "ANTI-MULLERIAN HORMONE (AMH), MALE",
      "Anti-Mullerian Hormone",
      "Anti-Mullerian Hormone (AMH)",
      "Anti-Mullerian Hormone (AMH), Female",
      "Anti-Mullerian Hormone (AMH), Male",
      "amh",
    ],
    unit: "ng/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Informational marker per Melissa — no fixed range. Surfaced for clinician review.",
  },
  estradiol: {
    canonicalName: "Estradiol (E2)",
    aliases: [
      "E2",
      "ESTRADIOL",
      "Estradiol",
      "Estradiol (E2)",
      "estradiol",
    ],
    unit: "pg/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    cyclePhaseDependent: true,
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Cycle-phase dependent. Flag against the lab-supplied range printed on the report.",
  },
  estrone: {
    canonicalName: "Estrone (E1)",
    aliases: [
      "E1",
      "ESTRONE",
      "Estrone",
      "Estrone (E1)",
      "estrone",
    ],
    unit: "pg/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    cyclePhaseDependent: true,
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Cycle-phase dependent. Flag against the lab-supplied range printed on the report.",
  },
  estriol: {
    canonicalName: "Estriol (E3)",
    aliases: [
      "E3",
      "ESTRIOL",
      "Estriol",
      "Estriol (E3)",
      "estriol",
    ],
    unit: "ng/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    cyclePhaseDependent: true,
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Cycle-phase dependent. Flag against the lab-supplied range printed on the report.",
  },

  // ----- Vitamin D variants (no Melissa-supplied ranges — refer to lab report) -----
  vitamin_d_1_25_oh2_total: {
    canonicalName: "Vitamin D 1,25 (OH)2 Total",
    aliases: [
      "1,25 DIHYDROXYVITAMIN D",
      "1,25-Dihydroxyvitamin D",
      "Calcitriol",
      "VITAMIN D 1,25 (OH)2",
      "VITAMIN D 1,25 (OH)2 TOTAL",
      "VITAMIN D, 1,25 (OH)2",
      "VITAMIN D, 1,25 (OH)2, TOTAL",
      "Vitamin D 1,25 (OH)2",
      "Vitamin D 1,25 (OH)2 Total",
      "Vitamin D, 1,25 (OH)2",
      "Vitamin D, 1,25 (OH)2, Total",
      "Vitamin D, 1,25-Dihydroxy",
      "vitamin d 1,25 (oh)2 total",
    ],
    unit: "pg/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  vitamin_d2: {
    canonicalName: "Vitamin D2",
    aliases: [
      "Ergocalciferol",
      "VITAMIN D2",
      "VITAMIN D2 (ERGOCALCIFEROL)",
      "VITAMIN D2, 1,25 (OH)2",
      "Vitamin D2",
      "Vitamin D2 (Ergocalciferol)",
      "Vitamin D2, 1,25 (OH)2",
      "vitamin d2",
    ],
    unit: "ng/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  vitamin_d3: {
    canonicalName: "Vitamin D3",
    aliases: [
      "Cholecalciferol",
      "VITAMIN D3",
      "VITAMIN D3 (CHOLECALCIFEROL)",
      "VITAMIN D3, 1,25 (OH)2",
      "Vitamin D3",
      "Vitamin D3 (Cholecalciferol)",
      "Vitamin D3, 1,25 (OH)2",
      "vitamin d3",
    ],
    unit: "ng/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },

  // ----- Omega panel (no Melissa-supplied ranges — refer to lab report) -----
  epa: {
    canonicalName: "EPA",
    aliases: [
      "EPA",
      "Eicosapentaenoic Acid",
      "epa",
    ],
    unit: "%",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "lipid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  dha: {
    canonicalName: "DHA",
    aliases: [
      "DHA",
      "Docosahexaenoic Acid",
      "dha",
    ],
    unit: "%",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "lipid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  dpa: {
    canonicalName: "DPA",
    aliases: [
      "DPA",
      "Docosapentaenoic Acid",
      "dpa",
    ],
    unit: "%",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "lipid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  omega_3_total: {
    canonicalName: "Omega-3 Total",
    aliases: [
      "OMEGA-3 TOTAL",
      "Omega 3 Total",
      "Omega-3 Total",
      "Total Omega-3",
      "omega-3 total",
    ],
    unit: "%",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "lipid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  omega_6_total: {
    canonicalName: "Omega-6 Total",
    aliases: [
      "OMEGA-6 TOTAL",
      "Omega 6 Total",
      "Omega-6 Total",
      "Total Omega-6",
      "omega-6 total",
    ],
    unit: "%",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "lipid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  omega_6_3_ratio: {
    canonicalName: "Omega-6/Omega-3 Ratio",
    aliases: [
      "OMEGA-6/OMEGA-3 RATIO",
      "Omega 6/3 Ratio",
      "Omega-6/Omega-3 Ratio",
      "Omega-6:Omega-3",
      "omega-6/omega-3 ratio",
    ],
    unit: "",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "lipid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  arachidonic_acid: {
    canonicalName: "Arachidonic Acid",
    aliases: [
      "AA",
      "ARACHIDONIC ACID",
      "Arachidonic Acid",
      "arachidonic acid",
    ],
    unit: "%",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "lipid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  arachidonic_acid_epa_ratio: {
    canonicalName: "Arachidonic Acid/EPA Ratio",
    aliases: [
      "AA/EPA",
      "AA/EPA RATIO",
      "ARACHIDONIC ACID/EPA RATIO",
      "Arachidonic Acid/EPA Ratio",
      "arachidonic acid/epa ratio",
    ],
    unit: "",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "lipid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  linoleic_acid: {
    canonicalName: "Linoleic Acid",
    aliases: [
      "LINOLEIC ACID",
      "LA",
      "Linoleic Acid",
      "linoleic acid",
    ],
    unit: "%",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "lipid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — no fixed range supplied.",
  },
  omega_check: {
    canonicalName: "Omega Check",
    aliases: [
      "OMEGA CHECK",
      "Omega Check",
      "OmegaCheck",
      "omega check",
    ],
    unit: "%",
    labRange: { min: 5.4, max: null },
    optimalRange: { min: null, max: null },
    interpretationBands: [
      { label: "High", min: null, max: 5.4, severity: "abnormal" },
      { label: "Optimal", min: 5.4, max: null, severity: "normal" },
    ],
    flagType: "three_tier_band",
    bandDirection: "higher_is_better",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "lipid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Two-tier marker per Melissa: >5.4 is optimal, anything below flags. Encoded as three_tier_band with no moderate band — flagging engine treats below-cutoff as 'high' severity.",
  },

  // ----- PSA panel -----
  psa_total: {
    canonicalName: "PSA Total",
    aliases: [
      "PROSTATE SPECIFIC AG",
      "PROSTATE SPECIFIC ANTIGEN",
      "PROSTATE SPECIFIC ANTIGEN, TOTAL",
      "PSA",
      "PSA TOTAL",
      "PSA Total",
      "PSA, Total",
      "Prostate Specific Antigen",
      "Prostate Specific Antigen, Total",
      "psa total",
    ],
    unit: "ng/mL",
    labRange: { min: null, max: 4.0 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    flaggedAboveCutoff: true,
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Flag if value >= 4.00 ng/mL (Melissa).",
  },
  psa_free: {
    canonicalName: "PSA Free",
    aliases: [
      "FREE PSA",
      "Free PSA",
      "PSA FREE",
      "PSA Free",
      "PSA, Free",
      "psa free",
    ],
    unit: "ng/mL",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Calculated component of the PSA panel — flagged via PSA % Free, no independent cutoff per Melissa.",
  },
  psa_percent_free: {
    canonicalName: "PSA % Free",
    aliases: [
      "% FREE PSA",
      "% Free PSA",
      "PSA % FREE",
      "PSA % Free",
      "PSA, % Free",
      "psa % free",
    ],
    unit: "%",
    labRange: { min: 25, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Flag if value < 25% (Melissa). Lower values raise prostate cancer risk independent of PSA Total.",
  },

  // ----- Heavy metals -----
  lead_venous: {
    canonicalName: "Lead Venous",
    aliases: [
      "LEAD",
      "LEAD VENOUS",
      "LEAD, BLOOD",
      "Lead",
      "Lead Venous",
      "Lead, Blood",
      "Pb",
      "lead venous",
    ],
    unit: "ug/dL",
    labRange: { min: null, max: 3.5 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    flaggedAboveCutoff: true,
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "vitamins_minerals",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Flag if value >= 3.5 ug/dL (Melissa).",
  },
  mercury_blood: {
    canonicalName: "Mercury Blood",
    aliases: [
      "Hg",
      "MERCURY",
      "MERCURY BLOOD",
      "MERCURY, BLOOD",
      "Mercury",
      "Mercury Blood",
      "Mercury, Blood",
      "mercury blood",
    ],
    unit: "ug/L",
    labRange: { min: null, max: 10 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    flaggedAboveCutoff: true,
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "vitamins_minerals",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Flag if value >= 10 ug/L (Melissa).",
  },

  // ----- Other Melissa-supplied markers -----
  leptin: {
    canonicalName: "Leptin",
    aliases: [
      "LEPTIN",
      "Leptin",
      "leptin",
    ],
    unit: "ng/mL",
    labRange: { min: 4.7, max: 23.7 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "endocrine",
    increaseCauses: [],
    decreaseCauses: [],
  },
  methylmalonic_acid: {
    canonicalName: "Methylmalonic Acid",
    aliases: [
      "MMA",
      "METHYLMALONIC ACID",
      "Methylmalonic Acid",
      "Methylmalonic Acid, Serum",
      "methylmalonic acid",
    ],
    unit: "nmol/L",
    labRange: { min: 55, max: 335 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "vitamins_minerals",
    increaseCauses: [],
    decreaseCauses: [],
  },
  amylase: {
    canonicalName: "Amylase",
    aliases: [
      "AMYLASE",
      "Amylase",
      "Amylase, Serum",
      "amylase",
    ],
    unit: "U/L",
    labRange: { min: 21, max: 101 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "liver",
    increaseCauses: [],
    decreaseCauses: [],
  },
  lipase: {
    canonicalName: "Lipase",
    aliases: [
      "LIPASE",
      "Lipase",
      "Lipase, Serum",
      "lipase",
    ],
    unit: "U/L",
    labRange: { min: 7, max: 60 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "liver",
    increaseCauses: [],
    decreaseCauses: [],
  },
  rheumatoid_factor: {
    canonicalName: "Rheumatoid Factor",
    aliases: [
      "RF",
      "RHEUMATOID FACTOR",
      "Rheumatoid Factor",
      "rheumatoid factor",
    ],
    unit: "IU/mL",
    labRange: { min: null, max: 10 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    flaggedAboveCutoff: true,
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27; reclassified to lab_range_only per email 2026-05-31",
    category: "immune_thyroid",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Reclassified from categorical to numeric cutoff per Melissa email 2026-05-31. Quest reports as numeric value <10 = negative.",
  },
  abo_group: {
    canonicalName: "ABO Group",
    aliases: [
      "ABO",
      "ABO GROUP",
      "ABO Group",
      "Blood Type",
      "abo group",
    ],
    unit: "",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "categorical",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "hematology",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Informational marker — no expectedValue. Engine returns flagStatus: 'informational'.",
  },
  mthfr: {
    canonicalName: "MTHFR",
    aliases: [
      "MTHFR",
      "MTHFR Genotype",
      "MTHFR Mutation",
      "MTHFR Variant",
      "mthfr",
    ],
    unit: "",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "categorical",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "vitamins_minerals",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Informational genetic marker — no expectedValue. Engine returns flagStatus: 'informational'.",
  },
  egfr: {
    canonicalName: "eGFR",
    aliases: [
      "EGFR",
      "ESTIMATED GFR",
      "Estimated GFR",
      "GFR",
      "Glomerular Filtration Rate",
      "eGFR",
      "egfr",
    ],
    unit: "mL/min/1.73m2",
    labRange: { min: 60, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "kidney",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Flag if value < 60 (Melissa). Lower = worse kidney function.",
  },
  magnesium_rbc: {
    canonicalName: "Magnesium RBC",
    aliases: [
      "Magnesium RBC",
      "Magnesium, RBC",
      "RBC MAGNESIUM",
      "RBC Magnesium",
      "RED BLOOD CELL MAGNESIUM",
      "Red Blood Cell Magnesium",
      "rbc magnesium",
    ],
    unit: "mg/dL",
    labRange: { min: 1.5, max: 2.5 },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "vitamins_minerals",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: 1.5-2.5 mg/dL. Distinct from serum magnesium — intracellular measure.",
  },

  // ----- Urinalysis (lab_range_only — ranges from Quest report) -----
  albumin_urine: {
    canonicalName: "Albumin Urine",
    aliases: [
      "ALBUMIN URINE",
      "ALBUMIN, URINE",
      "Albumin Urine",
      "Albumin, Urine",
      "Urine Albumin",
      "albumin urine",
    ],
    unit: "mg/L",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "kidney",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — flag against the printed Quest range.",
  },
  specific_gravity: {
    canonicalName: "Specific Gravity",
    aliases: [
      "SP. GRAVITY",
      "SPECIFIC GRAVITY",
      "Sp. Gravity",
      "Specific Gravity",
      "Urine Specific Gravity",
      "specific gravity",
    ],
    unit: "",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "kidney",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — flag against the printed Quest range.",
  },
  urine_ph: {
    canonicalName: "Urine pH",
    aliases: [
      "PH",
      "URINE PH",
      "Urine pH",
      "pH",
      "pH, Urine",
      "urine ph",
    ],
    unit: "",
    labRange: { min: null, max: null },
    optimalRange: { min: null, max: null },
    flagType: "lab_range_only",
    confirmationSource: "Melissa Carbone, tracking form template, email 2026-05-27",
    category: "kidney",
    increaseCauses: [],
    decreaseCauses: [],
    notes: "Per Melissa: refer to lab report — flag against the printed Quest range.",
  },
};

// Reverse lookup: given any alias (case-insensitive), find the canonical record.
const ALIAS_INDEX = (() => {
  const idx = new Map<string, MarkerRange>();
  for (const rec of Object.values(OPTIMAL_RANGES)) {
    idx.set(rec.canonicalName.toLowerCase(), rec);
    for (const a of rec.aliases) idx.set(a.toLowerCase(), rec);
  }
  return idx;
})();

export interface FoundMarker extends MarkerRange {
  /** True when the marker is still missing a confirmationSource (or carries
   *  the legacy requiresConfirmation flag). Callers should attach a
   *  "range pending confirmation from Melissa" note when flagging. */
  isUnconfirmed: boolean;
}

export function findMarker(name: string): FoundMarker | undefined {
  const rec = ALIAS_INDEX.get(name.toLowerCase().trim());
  if (!rec) return undefined;
  return { ...rec, isUnconfirmed: isUnconfirmed(rec) };
}

/** A marker is "unconfirmed" when it explicitly opted in via the legacy
 *  requiresConfirmation flag (and didn't yet supply a confirmationSource).
 *  Post-2026-05-27 refactor, none of the bundled markers should hit this
 *  branch — it remains as a safety net for future additions. */
export function isUnconfirmed(marker: MarkerRange): boolean {
  if (marker.requiresConfirmation !== true) return false;
  return !marker.confirmationSource;
}

/**
 * Returns false only for markers whose ranges are explicitly still pending
 * confirmation (legacy requiresConfirmation + missing source). The flagging
 * engine should still flag these but attach a "pending confirmation" note.
 */
export function isRangeUsable(marker: MarkerRange): boolean {
  return !isUnconfirmed(marker);
}
